/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.Treatment;

/**
 *
 * @author mateu
 */
public class NewTreatmentJDialog extends javax.swing.JDialog {

    private final View.MainJFrame frame;
    private final String animalName;
    private final String clientName;
    
    /** Creates new form NewTreatmentJDialog */
    public NewTreatmentJDialog(View.MainJFrame frame, boolean modal, String animalName, String clientName) {
        super(frame, modal);
        this.frame = frame;
        this.animalName = animalName;
        this.clientName = clientName;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFrame = new javax.swing.JPanel();
        jPanelNewTreatmentTittle = new javax.swing.JPanel();
        jLabelNewTreatmentTittle = new javax.swing.JLabel();
        jPanelNewTreatmentForm = new javax.swing.JPanel();
        jLabelNewTreatmentName = new javax.swing.JLabel();
        jTextFieldNewTreatmentName = new javax.swing.JTextField();
        jLabelNewTreatmentStartDay = new javax.swing.JLabel();
        jTextFieldNewTreatmentStartDay = new javax.swing.JFormattedTextField();
        jLabelNewTreatmentEndDay = new javax.swing.JLabel();
        jTextFieldNewTreatmentEndDay = new javax.swing.JFormattedTextField();
        jLabelNewTreatmentAnimalName = new javax.swing.JLabel();
        jTextFieldNewTreatmentAnimalName = new javax.swing.JTextField();
        jLabelNewTreatmentClientName = new javax.swing.JLabel();
        jTextFieldNewTreatmentClientName = new javax.swing.JTextField();
        jButtonNewTreatmentRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Treatment");
        setResizable(false);

        jPanelFrame.setToolTipText("");

        jPanelNewTreatmentTittle.setLayout(new java.awt.BorderLayout());

        jLabelNewTreatmentTittle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelNewTreatmentTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNewTreatmentTittle.setText("New Treatment");
        jPanelNewTreatmentTittle.add(jLabelNewTreatmentTittle, java.awt.BorderLayout.CENTER);

        jLabelNewTreatmentName.setText("Name");

        jTextFieldNewTreatmentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNewTreatmentNameActionPerformed(evt);
            }
        });

        jLabelNewTreatmentStartDay.setText("Start Day");

        try {
            jTextFieldNewTreatmentStartDay.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldNewTreatmentStartDay.setText("");

        jLabelNewTreatmentEndDay.setText("End Day");

        try {
            jTextFieldNewTreatmentEndDay.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldNewTreatmentEndDay.setText("");

        jLabelNewTreatmentAnimalName.setText("Animal");

        jTextFieldNewTreatmentAnimalName.setEditable(false);
        jTextFieldNewTreatmentAnimalName.setText(this.animalName);
        jTextFieldNewTreatmentAnimalName.setDisabledTextColor(java.awt.Color.black);
        jTextFieldNewTreatmentAnimalName.setEnabled(false);

        jLabelNewTreatmentClientName.setText("Client");

        jTextFieldNewTreatmentClientName.setEditable(false);
        jTextFieldNewTreatmentClientName.setText(this.clientName);
        jTextFieldNewTreatmentClientName.setDisabledTextColor(java.awt.Color.black);
        jTextFieldNewTreatmentClientName.setEnabled(false);

        jButtonNewTreatmentRegister.setText("Register");
        jButtonNewTreatmentRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNewTreatmentRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewTreatmentRegisterActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelNewTreatmentFormLayout = new org.jdesktop.layout.GroupLayout(jPanelNewTreatmentForm);
        jPanelNewTreatmentForm.setLayout(jPanelNewTreatmentFormLayout);
        jPanelNewTreatmentFormLayout.setHorizontalGroup(
            jPanelNewTreatmentFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelNewTreatmentFormLayout.createSequentialGroup()
                .add(jPanelNewTreatmentFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabelNewTreatmentEndDay, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabelNewTreatmentStartDay, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabelNewTreatmentName)
                    .add(jLabelNewTreatmentAnimalName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabelNewTreatmentClientName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewTreatmentFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTextFieldNewTreatmentName)
                    .add(jTextFieldNewTreatmentStartDay)
                    .add(jTextFieldNewTreatmentEndDay)
                    .add(jTextFieldNewTreatmentAnimalName)
                    .add(jTextFieldNewTreatmentClientName)))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelNewTreatmentFormLayout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .add(jButtonNewTreatmentRegister)
                .add(151, 151, 151))
        );
        jPanelNewTreatmentFormLayout.setVerticalGroup(
            jPanelNewTreatmentFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelNewTreatmentFormLayout.createSequentialGroup()
                .add(jPanelNewTreatmentFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jTextFieldNewTreatmentName)
                    .add(jLabelNewTreatmentName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewTreatmentFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jTextFieldNewTreatmentStartDay)
                    .add(jLabelNewTreatmentStartDay, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewTreatmentFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTextFieldNewTreatmentEndDay)
                    .add(jLabelNewTreatmentEndDay, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewTreatmentFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelNewTreatmentAnimalName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldNewTreatmentAnimalName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewTreatmentFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelNewTreatmentClientName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldNewTreatmentClientName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(62, 62, 62)
                .add(jButtonNewTreatmentRegister))
        );

        org.jdesktop.layout.GroupLayout jPanelFrameLayout = new org.jdesktop.layout.GroupLayout(jPanelFrame);
        jPanelFrame.setLayout(jPanelFrameLayout);
        jPanelFrameLayout.setHorizontalGroup(
            jPanelFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelNewTreatmentTittle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFrameLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelNewTreatmentForm, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelFrameLayout.setVerticalGroup(
            jPanelFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFrameLayout.createSequentialGroup()
                .add(jPanelNewTreatmentTittle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanelNewTreatmentForm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(37, 37, 37))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFrame, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFrame, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 289, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNewTreatmentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNewTreatmentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNewTreatmentNameActionPerformed

    private void jButtonNewTreatmentRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewTreatmentRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNewTreatmentRegisterActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNewTreatmentRegister;
    private javax.swing.JLabel jLabelNewTreatmentAnimalName;
    private javax.swing.JLabel jLabelNewTreatmentClientName;
    private javax.swing.JLabel jLabelNewTreatmentEndDay;
    private javax.swing.JLabel jLabelNewTreatmentName;
    private javax.swing.JLabel jLabelNewTreatmentStartDay;
    private javax.swing.JLabel jLabelNewTreatmentTittle;
    private javax.swing.JPanel jPanelFrame;
    private javax.swing.JPanel jPanelNewTreatmentForm;
    private javax.swing.JPanel jPanelNewTreatmentTittle;
    private javax.swing.JTextField jTextFieldNewTreatmentAnimalName;
    private javax.swing.JTextField jTextFieldNewTreatmentClientName;
    private javax.swing.JFormattedTextField jTextFieldNewTreatmentEndDay;
    private javax.swing.JTextField jTextFieldNewTreatmentName;
    private javax.swing.JFormattedTextField jTextFieldNewTreatmentStartDay;
    // End of variables declaration//GEN-END:variables

}
