/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.Client;

import Controller.ControllerAnimal;
import Controller.ControllerClient;

/**
 *
 * @author mateu
 */
public class EditClientJDialog extends javax.swing.JDialog {

    private final View.MainJFrame frame;
    private final int clientId;
    private final String clientName;
    private final String clientAddress;
    private final String clientPhone;
    private final String clientZipCode;
    private final String clientEmail;
    
    /** Creates new form EditClientJDialog */
    public EditClientJDialog(View.MainJFrame parent, boolean modal,  int clientId, String clientName, String clientAddress, String clientPhone, String clientZipCode, String clientEmail) {
        super(parent, modal);
        this.frame = parent;
        this.clientId = clientId;
        this.clientName = clientName;
        this.clientAddress = clientAddress;
        this.clientPhone = clientPhone;
        this.clientZipCode = clientZipCode;
        this.clientEmail = clientEmail;
        initComponents();
    }

    private String getCurrentClientName() {
        return this.jTextFieldEditClientName.getText();
    }
    
    private String getCurrentClientAddress() {
        return this.jTextFieldEditClientAddress.getText();
    }
    
    private String getCurrentClientPhone() {
        return this.jFormattedTextFieldEditClientPhone.getText().replace("(","").replace(")","").replace("-","");
    }
    
    private String getCurrentClientZipCode() {
        return this.jFormattedTextFieldEditClientZipCode.getText().replace("-","");
    }
    
    private String getCurrentClientEmail() {
        return this.jTextFieldEditClientEmail.getText();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFrame = new javax.swing.JPanel();
        jPanelEditClientTittle = new javax.swing.JPanel();
        jLabelEditClientTittle = new javax.swing.JLabel();
        jPanelEditClientForm = new javax.swing.JPanel();
        jLabelEditClientName = new javax.swing.JLabel();
        jTextFieldEditClientName = new javax.swing.JTextField();
        jLabelEditClientPhone = new javax.swing.JLabel();
        jFormattedTextFieldEditClientPhone = new javax.swing.JFormattedTextField();
        jLabelEditClientZipCode = new javax.swing.JLabel();
        jFormattedTextFieldEditClientZipCode = new javax.swing.JFormattedTextField();
        jLabelEditClientEmail = new javax.swing.JLabel();
        jTextFieldEditClientEmail = new javax.swing.JTextField();
        jLabelEditClientAddress = new javax.swing.JLabel();
        jTextFieldEditClientAddress = new javax.swing.JTextField();
        jButtonEditClientNewAnimal = new javax.swing.JButton();
        jButtonEditClientConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Client");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanelEditClientTittle.setLayout(new java.awt.BorderLayout());

        jLabelEditClientTittle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelEditClientTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEditClientTittle.setText("Edit Client");
        jPanelEditClientTittle.add(jLabelEditClientTittle, java.awt.BorderLayout.CENTER);

        jLabelEditClientName.setText("Name");

        jTextFieldEditClientName.setText(this.clientName);

        jLabelEditClientPhone.setText("Phone");

        try {
            jFormattedTextFieldEditClientPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldEditClientPhone.setText(this.clientPhone);

        jLabelEditClientZipCode.setText("Zip Code");

        try {
            jFormattedTextFieldEditClientZipCode.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldEditClientZipCode.setText(this.clientZipCode);

        jLabelEditClientEmail.setText("Email");

        jTextFieldEditClientEmail.setText(this.clientEmail);

        jLabelEditClientAddress.setText("Address");

        jTextFieldEditClientAddress.setText(this.clientAddress);

        jButtonEditClientNewAnimal.setText("New Animal");
        jButtonEditClientNewAnimal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEditClientNewAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditClientNewAnimalActionPerformed(evt);
            }
        });

        jButtonEditClientConfirm.setText("Update");
        jButtonEditClientConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEditClientConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditClientConfirmActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelEditClientFormLayout = new org.jdesktop.layout.GroupLayout(jPanelEditClientForm);
        jPanelEditClientForm.setLayout(jPanelEditClientFormLayout);
        jPanelEditClientFormLayout.setHorizontalGroup(
            jPanelEditClientFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelEditClientFormLayout.createSequentialGroup()
                .add(jPanelEditClientFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(jLabelEditClientName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabelEditClientPhone, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabelEditClientZipCode, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabelEditClientEmail, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabelEditClientAddress, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelEditClientFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTextFieldEditClientName)
                    .add(jFormattedTextFieldEditClientZipCode)
                    .add(jTextFieldEditClientEmail)
                    .add(jTextFieldEditClientAddress)
                    .add(jFormattedTextFieldEditClientPhone)))
            .add(jPanelEditClientFormLayout.createSequentialGroup()
                .add(jPanelEditClientFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelEditClientFormLayout.createSequentialGroup()
                        .add(154, 154, 154)
                        .add(jButtonEditClientConfirm))
                    .add(jPanelEditClientFormLayout.createSequentialGroup()
                        .add(144, 144, 144)
                        .add(jButtonEditClientNewAnimal)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelEditClientFormLayout.setVerticalGroup(
            jPanelEditClientFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelEditClientFormLayout.createSequentialGroup()
                .add(jPanelEditClientFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelEditClientName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldEditClientName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelEditClientFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelEditClientPhone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jFormattedTextFieldEditClientPhone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelEditClientFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelEditClientZipCode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jFormattedTextFieldEditClientZipCode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelEditClientFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jTextFieldEditClientEmail)
                    .add(jLabelEditClientEmail, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelEditClientFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldEditClientAddress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelEditClientAddress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButtonEditClientNewAnimal)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonEditClientConfirm))
        );

        org.jdesktop.layout.GroupLayout jPanelFrameLayout = new org.jdesktop.layout.GroupLayout(jPanelFrame);
        jPanelFrame.setLayout(jPanelFrameLayout);
        jPanelFrameLayout.setHorizontalGroup(
            jPanelFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelEditClientTittle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFrameLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelEditClientForm, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelFrameLayout.setVerticalGroup(
            jPanelFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFrameLayout.createSequentialGroup()
                .add(jPanelEditClientTittle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelEditClientForm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFrame, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFrame, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditClientNewAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditClientNewAnimalActionPerformed
        try {
            ControllerAnimal.showNewAnimalJDialogFromEditClient(this.frame,this.clientId,this.clientName);
        } catch (Exception ex) {
            System.out.println(ex);
            javax.swing.JOptionPane.showMessageDialog(this.frame,ex);
        }
    }//GEN-LAST:event_jButtonEditClientNewAnimalActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            ControllerClient.showSeeClientJDialogFromClientId(this.frame, this.clientId);
        } catch (Exception ex) {
            System.out.println(ex);
            javax.swing.JOptionPane.showMessageDialog(this.frame, ex);
        }
    }//GEN-LAST:event_formWindowClosed

    private void jButtonEditClientConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditClientConfirmActionPerformed
        try {
            ControllerClient.editClient(this.clientId,this.getCurrentClientName(),this.getCurrentClientPhone(),this.getCurrentClientZipCode(),this.getCurrentClientEmail(),this.getCurrentClientAddress());
            ControllerClient.showDataTableAll(this.frame.getTableComponentsCollection(),this.frame.getTableComponentsClients());
            this.dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println(ex);
            javax.swing.JOptionPane.showMessageDialog(this.frame,ex);
        }
    }//GEN-LAST:event_jButtonEditClientConfirmActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditClientConfirm;
    private javax.swing.JButton jButtonEditClientNewAnimal;
    private javax.swing.JFormattedTextField jFormattedTextFieldEditClientPhone;
    private javax.swing.JFormattedTextField jFormattedTextFieldEditClientZipCode;
    private javax.swing.JLabel jLabelEditClientAddress;
    private javax.swing.JLabel jLabelEditClientEmail;
    private javax.swing.JLabel jLabelEditClientName;
    private javax.swing.JLabel jLabelEditClientPhone;
    private javax.swing.JLabel jLabelEditClientTittle;
    private javax.swing.JLabel jLabelEditClientZipCode;
    private javax.swing.JPanel jPanelEditClientForm;
    private javax.swing.JPanel jPanelEditClientTittle;
    private javax.swing.JPanel jPanelFrame;
    private javax.swing.JTextField jTextFieldEditClientAddress;
    private javax.swing.JTextField jTextFieldEditClientEmail;
    private javax.swing.JTextField jTextFieldEditClientName;
    // End of variables declaration//GEN-END:variables

}
