/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.Client;

import Controller.ControllerClient;

/**
 *
 * @author mateu
 */
public class NewClientJDialog extends javax.swing.JDialog {

    private final View.MainJFrame frame;
    
    /** Creates new form NewClientJDialog */
    public NewClientJDialog(View.MainJFrame frame, boolean modal) {
        super(frame, modal);
        this.frame = frame;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFrame = new javax.swing.JPanel();
        jPanelNewClientTittle = new javax.swing.JPanel();
        jLabelNewClientTittle = new javax.swing.JLabel();
        jPanelNewClientForm = new javax.swing.JPanel();
        jLabelNewClientName = new javax.swing.JLabel();
        jTextFieldNewClientName = new javax.swing.JTextField();
        jLabelNewClientPhone = new javax.swing.JLabel();
        jFormattedTextFieldNewClientPhone = new javax.swing.JFormattedTextField();
        jLabelNewClientZipCode = new javax.swing.JLabel();
        jFormattedTextFieldNewClientZipCode = new javax.swing.JFormattedTextField();
        jLabelNewClientEmail = new javax.swing.JLabel();
        jTextFieldNewClientEmail = new javax.swing.JTextField();
        jLabelNewClientAddress = new javax.swing.JLabel();
        jTextFieldNewClientAddress = new javax.swing.JTextField();
        jButtonNewClientConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Client");
        setResizable(false);

        jPanelNewClientTittle.setLayout(new java.awt.BorderLayout());

        jLabelNewClientTittle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelNewClientTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNewClientTittle.setText("New Client");
        jPanelNewClientTittle.add(jLabelNewClientTittle, java.awt.BorderLayout.CENTER);

        jLabelNewClientName.setText("Name");

        jLabelNewClientPhone.setText("Phone");

        try {
            jFormattedTextFieldNewClientPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelNewClientZipCode.setText("Zip Code");

        try {
            jFormattedTextFieldNewClientZipCode.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelNewClientEmail.setText("Email");

        jLabelNewClientAddress.setText("Address");

        jButtonNewClientConfirm.setText("Register");
        jButtonNewClientConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNewClientConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewClientConfirmActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelNewClientFormLayout = new org.jdesktop.layout.GroupLayout(jPanelNewClientForm);
        jPanelNewClientForm.setLayout(jPanelNewClientFormLayout);
        jPanelNewClientFormLayout.setHorizontalGroup(
            jPanelNewClientFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelNewClientFormLayout.createSequentialGroup()
                .add(154, 154, 154)
                .add(jButtonNewClientConfirm)
                .addContainerGap(153, Short.MAX_VALUE))
            .add(jPanelNewClientFormLayout.createSequentialGroup()
                .add(jPanelNewClientFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(jLabelNewClientName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabelNewClientPhone, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabelNewClientZipCode, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabelNewClientEmail, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabelNewClientAddress, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewClientFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTextFieldNewClientName)
                    .add(jTextFieldNewClientEmail)
                    .add(jTextFieldNewClientAddress)
                    .add(jFormattedTextFieldNewClientZipCode)
                    .add(jFormattedTextFieldNewClientPhone)))
        );
        jPanelNewClientFormLayout.setVerticalGroup(
            jPanelNewClientFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelNewClientFormLayout.createSequentialGroup()
                .add(jPanelNewClientFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelNewClientName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldNewClientName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewClientFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelNewClientPhone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jFormattedTextFieldNewClientPhone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewClientFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelNewClientZipCode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jFormattedTextFieldNewClientZipCode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewClientFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jTextFieldNewClientEmail)
                    .add(jLabelNewClientEmail, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewClientFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldNewClientAddress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelNewClientAddress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButtonNewClientConfirm))
        );

        org.jdesktop.layout.GroupLayout jPanelFrameLayout = new org.jdesktop.layout.GroupLayout(jPanelFrame);
        jPanelFrame.setLayout(jPanelFrameLayout);
        jPanelFrameLayout.setHorizontalGroup(
            jPanelFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelNewClientTittle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFrameLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelNewClientForm, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelFrameLayout.setVerticalGroup(
            jPanelFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFrameLayout.createSequentialGroup()
                .add(jPanelNewClientTittle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewClientForm, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFrame, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFrame, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewClientConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewClientConfirmActionPerformed
        try {
            ControllerClient.newClient(this.jTextFieldNewClientName.getText(),this.jFormattedTextFieldNewClientPhone.getText().replace("(","").replace(")","").replace("-",""),this.jFormattedTextFieldNewClientZipCode.getText().replace("-",""),this.jTextFieldNewClientEmail.getText(),this.jTextFieldNewClientAddress.getText());
            ControllerClient.showDataTableAll(this.frame.getTableComponentsCollection(),this.frame.getTableComponentsClients());
            this.dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println(ex);
            javax.swing.JOptionPane.showMessageDialog(this.frame,ex);
        }
    }//GEN-LAST:event_jButtonNewClientConfirmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNewClientConfirm;
    private javax.swing.JFormattedTextField jFormattedTextFieldNewClientPhone;
    private javax.swing.JFormattedTextField jFormattedTextFieldNewClientZipCode;
    private javax.swing.JLabel jLabelNewClientAddress;
    private javax.swing.JLabel jLabelNewClientEmail;
    private javax.swing.JLabel jLabelNewClientName;
    private javax.swing.JLabel jLabelNewClientPhone;
    private javax.swing.JLabel jLabelNewClientTittle;
    private javax.swing.JLabel jLabelNewClientZipCode;
    private javax.swing.JPanel jPanelFrame;
    private javax.swing.JPanel jPanelNewClientForm;
    private javax.swing.JPanel jPanelNewClientTittle;
    private javax.swing.JTextField jTextFieldNewClientAddress;
    private javax.swing.JTextField jTextFieldNewClientEmail;
    private javax.swing.JTextField jTextFieldNewClientName;
    // End of variables declaration//GEN-END:variables

}
