/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.Vet;

import Controller.ControllerVet;

/**
 *
 * @author mateu
 */
public class NewVetJDialog extends javax.swing.JDialog {

    private final View.MainJFrame frame;
    
    /** Creates new form NewVetJDialog */
    public NewVetJDialog(View.MainJFrame frame, boolean modal) {
        super(frame, modal);
        this.frame = frame;
        initComponents();
    }

    private String getCurrentVetName() {
        return this.jTextFieldNewVetName.getText();
    }
    
    private String getCurrentVetPhone() {
        return this.jFormattedTextFieldNewVetPhone.getText().replace("(","").replace(")","").replace("-","");
    }
    
    private String getCurrentVetAddress() {
        return this.jTextFieldNewVetAddress.getText();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFrame = new javax.swing.JPanel();
        jPanelNewVetTittle = new javax.swing.JPanel();
        jLabelNewVetTittle = new javax.swing.JLabel();
        jPanelNewVetForm = new javax.swing.JPanel();
        jLabelNewVetName = new javax.swing.JLabel();
        jTextFieldNewVetName = new javax.swing.JTextField();
        jLabelNewVetPhone = new javax.swing.JLabel();
        jFormattedTextFieldNewVetPhone = new javax.swing.JFormattedTextField();
        jLabelNewVetAddress = new javax.swing.JLabel();
        jTextFieldNewVetAddress = new javax.swing.JTextField();
        jButtonNewVetConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Vet");
        setResizable(false);

        jPanelNewVetTittle.setLayout(new java.awt.BorderLayout());

        jLabelNewVetTittle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelNewVetTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNewVetTittle.setText("New Vet");
        jPanelNewVetTittle.add(jLabelNewVetTittle, java.awt.BorderLayout.CENTER);

        jLabelNewVetName.setText("Name");

        jLabelNewVetPhone.setText("Phone");

        try {
            jFormattedTextFieldNewVetPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelNewVetAddress.setText("Address");

        jButtonNewVetConfirm.setText("Register");
        jButtonNewVetConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNewVetConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewVetConfirmActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelNewVetFormLayout = new org.jdesktop.layout.GroupLayout(jPanelNewVetForm);
        jPanelNewVetForm.setLayout(jPanelNewVetFormLayout);
        jPanelNewVetFormLayout.setHorizontalGroup(
            jPanelNewVetFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelNewVetFormLayout.createSequentialGroup()
                .add(jPanelNewVetFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabelNewVetAddress, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .add(jLabelNewVetPhone, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabelNewVetName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewVetFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTextFieldNewVetAddress)
                    .add(jFormattedTextFieldNewVetPhone)
                    .add(jTextFieldNewVetName)))
            .add(jPanelNewVetFormLayout.createSequentialGroup()
                .add(146, 146, 146)
                .add(jButtonNewVetConfirm)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jPanelNewVetFormLayout.setVerticalGroup(
            jPanelNewVetFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelNewVetFormLayout.createSequentialGroup()
                .add(jPanelNewVetFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelNewVetName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldNewVetName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewVetFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelNewVetPhone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jFormattedTextFieldNewVetPhone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewVetFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelNewVetAddress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldNewVetAddress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButtonNewVetConfirm))
        );

        org.jdesktop.layout.GroupLayout jPanelFrameLayout = new org.jdesktop.layout.GroupLayout(jPanelFrame);
        jPanelFrame.setLayout(jPanelFrameLayout);
        jPanelFrameLayout.setHorizontalGroup(
            jPanelFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelNewVetTittle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFrameLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelNewVetForm, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelFrameLayout.setVerticalGroup(
            jPanelFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFrameLayout.createSequentialGroup()
                .add(jPanelNewVetTittle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewVetForm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFrame, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFrame, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewVetConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewVetConfirmActionPerformed
        try {
            ControllerVet.newVet(this.getCurrentVetName(),this.getCurrentVetPhone(),this.getCurrentVetAddress());
            ControllerVet.showDataTableAll(this.frame.getTableComponentsCollection(),this.frame.getTableComponentsVets());
            this.dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println(ex);
            javax.swing.JOptionPane.showMessageDialog(this.frame,ex);
        }
    }//GEN-LAST:event_jButtonNewVetConfirmActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNewVetConfirm;
    private javax.swing.JFormattedTextField jFormattedTextFieldNewVetPhone;
    private javax.swing.JLabel jLabelNewVetAddress;
    private javax.swing.JLabel jLabelNewVetName;
    private javax.swing.JLabel jLabelNewVetPhone;
    private javax.swing.JLabel jLabelNewVetTittle;
    private javax.swing.JPanel jPanelFrame;
    private javax.swing.JPanel jPanelNewVetForm;
    private javax.swing.JPanel jPanelNewVetTittle;
    private javax.swing.JTextField jTextFieldNewVetAddress;
    private javax.swing.JTextField jTextFieldNewVetName;
    // End of variables declaration//GEN-END:variables

}
