/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.Vet;

import Controller.ControllerConsultation;
import Controller.ControllerExam;
import Controller.ControllerVet;

/**
 *
 * @author mateu
 */
public class SeeVetJDialog extends javax.swing.JDialog {

    private final View.MainJFrame frame;
    private final int vetId;
    private final String vetName;
    private final String vetPhone;
    private final String vetAddress;
    
    /** Creates new form SeeVetJDialog */
    public SeeVetJDialog(View.MainJFrame frame, boolean modal, int vetId, String vetName, String vetPhone, String vetAddress) {
        super(frame, modal);
        this.frame = frame;
        this.vetId = vetId;
        this.vetName = vetName;
        this.vetPhone = vetPhone;
        this.vetAddress = vetAddress;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFrame = new javax.swing.JPanel();
        jPanelSeeVetTittle = new javax.swing.JPanel();
        jLabelSeeVetTittle = new javax.swing.JLabel();
        jPanelSeeVetActionButtons = new javax.swing.JPanel();
        jButtonSeeVetEditVet = new javax.swing.JButton();
        jButtonSeeVetDeleteVet = new javax.swing.JButton();
        jPanelSeeVetForm = new javax.swing.JPanel();
        jLabelSeeVetName = new javax.swing.JLabel();
        jTextFieldSeeVetName = new javax.swing.JTextField();
        jLabelSeeVetPhone = new javax.swing.JLabel();
        jFormattedTextFieldSeeVetPhone = new javax.swing.JFormattedTextField();
        jLabelSeeVetAddress = new javax.swing.JLabel();
        jTextFieldSeeVetAddress = new javax.swing.JTextField();
        jButtonSeeVetSeeConsultations = new javax.swing.JButton();
        jButtonSeeVetSeeExams = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("See Vet");
        setResizable(false);

        jPanelSeeVetTittle.setLayout(new java.awt.BorderLayout());

        jLabelSeeVetTittle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelSeeVetTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSeeVetTittle.setText("See Vet");
        jPanelSeeVetTittle.add(jLabelSeeVetTittle, java.awt.BorderLayout.CENTER);

        jPanelSeeVetActionButtons.setPreferredSize(new java.awt.Dimension(120, 50));

        jButtonSeeVetEditVet.setText("Edit");
        jButtonSeeVetEditVet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSeeVetEditVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeeVetEditVetActionPerformed(evt);
            }
        });

        jButtonSeeVetDeleteVet.setText("Delete");
        jButtonSeeVetDeleteVet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSeeVetDeleteVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeeVetDeleteVetActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelSeeVetActionButtonsLayout = new org.jdesktop.layout.GroupLayout(jPanelSeeVetActionButtons);
        jPanelSeeVetActionButtons.setLayout(jPanelSeeVetActionButtonsLayout);
        jPanelSeeVetActionButtonsLayout.setHorizontalGroup(
            jPanelSeeVetActionButtonsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelSeeVetActionButtonsLayout.createSequentialGroup()
                .add(jButtonSeeVetEditVet)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonSeeVetDeleteVet)
                .add(0, 0, Short.MAX_VALUE))
        );
        jPanelSeeVetActionButtonsLayout.setVerticalGroup(
            jPanelSeeVetActionButtonsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelSeeVetActionButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelSeeVetActionButtonsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonSeeVetEditVet)
                    .add(jButtonSeeVetDeleteVet))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelSeeVetTittle.add(jPanelSeeVetActionButtons, java.awt.BorderLayout.LINE_END);

        jLabelSeeVetName.setText("Name");

        jTextFieldSeeVetName.setEditable(false);
        jTextFieldSeeVetName.setText(this.vetName);
        jTextFieldSeeVetName.setDisabledTextColor(java.awt.Color.black);
        jTextFieldSeeVetName.setEnabled(false);

        jLabelSeeVetPhone.setText("Phone");

        jFormattedTextFieldSeeVetPhone.setEditable(false);
        try {
            jFormattedTextFieldSeeVetPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldSeeVetPhone.setText(this.vetPhone);
        jFormattedTextFieldSeeVetPhone.setDisabledTextColor(java.awt.Color.black);
        jFormattedTextFieldSeeVetPhone.setEnabled(false);

        jLabelSeeVetAddress.setText("Address");

        jTextFieldSeeVetAddress.setEditable(false);
        jTextFieldSeeVetAddress.setText(this.vetAddress);
        jTextFieldSeeVetAddress.setDisabledTextColor(java.awt.Color.black);
        jTextFieldSeeVetAddress.setEnabled(false);

        jButtonSeeVetSeeConsultations.setText("See Consultations");
        jButtonSeeVetSeeConsultations.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSeeVetSeeConsultations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeeVetSeeConsultationsActionPerformed(evt);
            }
        });

        jButtonSeeVetSeeExams.setText("See Exams");
        jButtonSeeVetSeeExams.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSeeVetSeeExams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeeVetSeeExamsActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelSeeVetFormLayout = new org.jdesktop.layout.GroupLayout(jPanelSeeVetForm);
        jPanelSeeVetForm.setLayout(jPanelSeeVetFormLayout);
        jPanelSeeVetFormLayout.setHorizontalGroup(
            jPanelSeeVetFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelSeeVetFormLayout.createSequentialGroup()
                .add(jPanelSeeVetFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabelSeeVetAddress, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .add(jLabelSeeVetPhone, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabelSeeVetName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelSeeVetFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTextFieldSeeVetAddress)
                    .add(jFormattedTextFieldSeeVetPhone)
                    .add(jTextFieldSeeVetName)))
            .add(jPanelSeeVetFormLayout.createSequentialGroup()
                .add(jButtonSeeVetSeeConsultations, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 187, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonSeeVetSeeExams, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
        );
        jPanelSeeVetFormLayout.setVerticalGroup(
            jPanelSeeVetFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelSeeVetFormLayout.createSequentialGroup()
                .add(jPanelSeeVetFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelSeeVetName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldSeeVetName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelSeeVetFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelSeeVetPhone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jFormattedTextFieldSeeVetPhone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelSeeVetFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelSeeVetAddress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldSeeVetAddress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelSeeVetFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonSeeVetSeeConsultations)
                    .add(jButtonSeeVetSeeExams)))
        );

        org.jdesktop.layout.GroupLayout jPanelFrameLayout = new org.jdesktop.layout.GroupLayout(jPanelFrame);
        jPanelFrame.setLayout(jPanelFrameLayout);
        jPanelFrameLayout.setHorizontalGroup(
            jPanelFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFrameLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelSeeVetForm, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFrameLayout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(jPanelSeeVetTittle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 345, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPanelFrameLayout.setVerticalGroup(
            jPanelFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFrameLayout.createSequentialGroup()
                .add(jPanelSeeVetTittle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelSeeVetForm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFrame, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFrame, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSeeVetEditVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeeVetEditVetActionPerformed
        try {
            this.dispose();
            ControllerVet.showEditVetJDialogFromVetId(this.frame, this.vetId);
        } catch (Exception ex) {
            System.out.println(ex);
            javax.swing.JOptionPane.showMessageDialog(this.frame, ex);
        }
    }//GEN-LAST:event_jButtonSeeVetEditVetActionPerformed

    private void jButtonSeeVetDeleteVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeeVetDeleteVetActionPerformed
        try {
            this.dispose();
            ControllerVet.showDeleteVetJDialogFromVetId(this.frame, this.vetId);
        } catch (Exception ex) {
            System.out.println(ex);
            javax.swing.JOptionPane.showMessageDialog(this.frame, ex);
        }
    }//GEN-LAST:event_jButtonSeeVetDeleteVetActionPerformed

    private void jButtonSeeVetSeeConsultationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeeVetSeeConsultationsActionPerformed
        try {
            ControllerConsultation.showDataTableByVetId(this.frame.getTableComponentsCollection(), this.frame.getTableComponentsConsultations(), this.vetId);
        } catch (Exception ex) {
            System.out.println(ex);
            javax.swing.JOptionPane.showMessageDialog(this.frame, ex);
        }
    }//GEN-LAST:event_jButtonSeeVetSeeConsultationsActionPerformed

    private void jButtonSeeVetSeeExamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeeVetSeeExamsActionPerformed
        try {
            ControllerExam.showDataTableByVetId(this.frame.getTableComponentsCollection(), this.frame.getTableComponentsExams(), this.vetId);
        } catch (Exception ex) {
            System.out.println(ex);
            javax.swing.JOptionPane.showMessageDialog(this.frame, ex);
        }
    }//GEN-LAST:event_jButtonSeeVetSeeExamsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSeeVetDeleteVet;
    private javax.swing.JButton jButtonSeeVetEditVet;
    private javax.swing.JButton jButtonSeeVetSeeConsultations;
    private javax.swing.JButton jButtonSeeVetSeeExams;
    private javax.swing.JFormattedTextField jFormattedTextFieldSeeVetPhone;
    private javax.swing.JLabel jLabelSeeVetAddress;
    private javax.swing.JLabel jLabelSeeVetName;
    private javax.swing.JLabel jLabelSeeVetPhone;
    private javax.swing.JLabel jLabelSeeVetTittle;
    private javax.swing.JPanel jPanelFrame;
    private javax.swing.JPanel jPanelSeeVetActionButtons;
    private javax.swing.JPanel jPanelSeeVetForm;
    private javax.swing.JPanel jPanelSeeVetTittle;
    private javax.swing.JTextField jTextFieldSeeVetAddress;
    private javax.swing.JTextField jTextFieldSeeVetName;
    // End of variables declaration//GEN-END:variables

}
