/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.Consultation;

import java.sql.SQLException;
import javax.swing.ComboBoxModel;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;

import View.MainJFrame;

import Controller.ControllerConsultation;

/**
 *
 * @author mateu
 */
public class EditConsultationJDialog extends javax.swing.JDialog {

    private final MainJFrame frame;
    private final int consultationId;
    private final LocalDateTime consultationLocalDateTime;
    private final String consultationComment;
    private final int treatmentId;
    private final String treatmentName;
    private final int animalId;
    private final String animalName;
    private final int clientId;
    private final String clientName;
    private final int vetId;
    private ComboBoxModel vetsComboModel;
    private boolean showSeeConsultationOnDispose = true;
    
    /** Creates new form EditConsultationJDialog */
    public EditConsultationJDialog(MainJFrame frame, boolean modal, int consultationId, LocalDateTime consultationLocalDateTime, String consultationComment, int treatmentId, String treatmentName, int animalId, String animalName, int clientId, String clientName, int vetId) throws SQLException, Exception {
        super(frame, modal);
        this.frame = frame;
        this.consultationId = consultationId;
        this.consultationLocalDateTime = consultationLocalDateTime;
        this.consultationComment = consultationComment;
        this.treatmentId = treatmentId;
        this.treatmentName = treatmentName;
        this.animalId = animalId;
        this.animalName = animalName;
        this.clientId = clientId;
        this.clientName = clientName;
        this.vetId = vetId;
        this.vetsComboModel = ControllerConsultation.getVetsComboModel(this.vetId);
        initComponents();
    }

    private LocalDate getConsultationDate() {
        return LocalDate.of(this.consultationLocalDateTime.getYear(), this.consultationLocalDateTime.getMonth(), this.consultationLocalDateTime.getDayOfMonth());
    }
    
    private LocalTime getConsultationTime() {
        return LocalTime.of(this.consultationLocalDateTime.getHour(), this.consultationLocalDateTime.getMinute());
    }
    
    private LocalDate getCurrentConsultationDate() {
        return LocalDate.parse(jFormattedTextFieldEditConsultationDate.getText());
    }
    
    private LocalTime getCurrentConsultationTime() {
        return LocalTime.parse(jFormattedTextFieldEditConsultationTime.getText());
    }
    
    private LocalDateTime getCurrentConsultationDateTime() {
        return LocalDateTime.of(getCurrentConsultationDate(),getCurrentConsultationTime());
    }
    
    private String getCurrentConsultationComment() {
        return jTextAreaEditConsultationComment.getText();
    }
    
    private String getCurrentSelectedVet() {
        return (String) this.vetsComboModel.getSelectedItem();
    }
    
    private int getCurrentSelectedVetId() {
        return ControllerConsultation.getComboModelSelectedVetId(this.vetsComboModel,this.getCurrentSelectedVet());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFrame = new javax.swing.JPanel();
        jPanelEditConsultationTittle = new javax.swing.JPanel();
        jLabelNewTreatmentTittle = new javax.swing.JLabel();
        jPanelEditConsultationForm = new javax.swing.JPanel();
        jLabelEditConsultationDate = new javax.swing.JLabel();
        jFormattedTextFieldEditConsultationDate = new javax.swing.JFormattedTextField();
        jLabelEditConsultationTime = new javax.swing.JLabel();
        jFormattedTextFieldEditConsultationTime = new javax.swing.JFormattedTextField();
        jLabelEditConsultationTreatmentName = new javax.swing.JLabel();
        jTextFieldEditConsultationTreatmentName = new javax.swing.JTextField();
        jLabelEditConsultationAnimalName = new javax.swing.JLabel();
        jTextFieldEditConsultationAnimalName = new javax.swing.JTextField();
        jLabelEditConsultationClientName = new javax.swing.JLabel();
        jTextFieldEditConsultationClientName = new javax.swing.JTextField();
        jLabelEditConsultationVetName = new javax.swing.JLabel();
        jLabelEditConsultationComment = new javax.swing.JLabel();
        jScrollPaneEditConsultationComment = new javax.swing.JScrollPane();
        jTextAreaEditConsultationComment = new javax.swing.JTextArea();
        jButtonEditConsultationNewExam = new javax.swing.JButton();
        jButtonEditConsultationUpdate = new javax.swing.JButton();
        jComboBoxNewConsultationVet = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Consultation");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanelEditConsultationTittle.setLayout(new java.awt.BorderLayout());

        jLabelNewTreatmentTittle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelNewTreatmentTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNewTreatmentTittle.setText("Edit Consultation");
        jPanelEditConsultationTittle.add(jLabelNewTreatmentTittle, java.awt.BorderLayout.CENTER);

        jLabelEditConsultationDate.setText("Date");

        try {
            jFormattedTextFieldEditConsultationDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldEditConsultationDate.setText(this.getConsultationDate().toString());

        jLabelEditConsultationTime.setText("Hour");

        try {
            jFormattedTextFieldEditConsultationTime.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldEditConsultationTime.setText(this.getConsultationTime().toString());

        jLabelEditConsultationTreatmentName.setText("Treatment");

        jTextFieldEditConsultationTreatmentName.setEditable(false);
        jTextFieldEditConsultationTreatmentName.setText(this.treatmentName);
        jTextFieldEditConsultationTreatmentName.setDisabledTextColor(java.awt.Color.black);
        jTextFieldEditConsultationTreatmentName.setEnabled(false);

        jLabelEditConsultationAnimalName.setText("Animal");

        jTextFieldEditConsultationAnimalName.setEditable(false);
        jTextFieldEditConsultationAnimalName.setText(this.animalName);
        jTextFieldEditConsultationAnimalName.setDisabledTextColor(java.awt.Color.black);
        jTextFieldEditConsultationAnimalName.setEnabled(false);

        jLabelEditConsultationClientName.setText("Client");

        jTextFieldEditConsultationClientName.setEditable(false);
        jTextFieldEditConsultationClientName.setText(this.clientName);
        jTextFieldEditConsultationClientName.setDisabledTextColor(java.awt.Color.black);
        jTextFieldEditConsultationClientName.setEnabled(false);

        jLabelEditConsultationVetName.setText("Vet");

        jLabelEditConsultationComment.setText("Comment");

        jTextAreaEditConsultationComment.setColumns(20);
        jTextAreaEditConsultationComment.setRows(5);
        jTextAreaEditConsultationComment.setText(this.consultationComment);
        jScrollPaneEditConsultationComment.setViewportView(jTextAreaEditConsultationComment);

        jButtonEditConsultationNewExam.setText("New Exam");
        jButtonEditConsultationNewExam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonEditConsultationUpdate.setText("Update");
        jButtonEditConsultationUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEditConsultationUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditConsultationUpdateActionPerformed(evt);
            }
        });

        jComboBoxNewConsultationVet.setModel(this.vetsComboModel);
        jComboBoxNewConsultationVet.setToolTipText("");
        jComboBoxNewConsultationVet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxNewConsultationVet.setEnabled(!ControllerConsultation.isVetsComboModelEmpty(this.vetsComboModel));

        org.jdesktop.layout.GroupLayout jPanelEditConsultationFormLayout = new org.jdesktop.layout.GroupLayout(jPanelEditConsultationForm);
        jPanelEditConsultationForm.setLayout(jPanelEditConsultationFormLayout);
        jPanelEditConsultationFormLayout.setHorizontalGroup(
            jPanelEditConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelEditConsultationFormLayout.createSequentialGroup()
                .add(jPanelEditConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabelEditConsultationTime, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabelEditConsultationDate, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabelEditConsultationTreatmentName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabelEditConsultationAnimalName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabelEditConsultationClientName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabelEditConsultationComment, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelEditConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jFormattedTextFieldEditConsultationDate)
                    .add(jFormattedTextFieldEditConsultationTime)
                    .add(jScrollPaneEditConsultationComment)
                    .add(jTextFieldEditConsultationTreatmentName)
                    .add(jTextFieldEditConsultationClientName)
                    .add(jTextFieldEditConsultationAnimalName)))
            .add(jPanelEditConsultationFormLayout.createSequentialGroup()
                .add(jLabelEditConsultationVetName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jComboBoxNewConsultationVet, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelEditConsultationFormLayout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .add(jPanelEditConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(jButtonEditConsultationNewExam, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jButtonEditConsultationUpdate, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(145, 145, 145))
        );
        jPanelEditConsultationFormLayout.setVerticalGroup(
            jPanelEditConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelEditConsultationFormLayout.createSequentialGroup()
                .add(jPanelEditConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jFormattedTextFieldEditConsultationDate)
                    .add(jLabelEditConsultationDate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelEditConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jFormattedTextFieldEditConsultationTime)
                    .add(jLabelEditConsultationTime, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelEditConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelEditConsultationTreatmentName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldEditConsultationTreatmentName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelEditConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldEditConsultationAnimalName)
                    .add(jLabelEditConsultationAnimalName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelEditConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldEditConsultationClientName)
                    .add(jLabelEditConsultationClientName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelEditConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelEditConsultationVetName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jComboBoxNewConsultationVet, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelEditConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPaneEditConsultationComment, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelEditConsultationComment))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonEditConsultationNewExam)
                .add(30, 30, 30)
                .add(jButtonEditConsultationUpdate))
        );

        org.jdesktop.layout.GroupLayout jPanelFrameLayout = new org.jdesktop.layout.GroupLayout(jPanelFrame);
        jPanelFrame.setLayout(jPanelFrameLayout);
        jPanelFrameLayout.setHorizontalGroup(
            jPanelFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelEditConsultationTittle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFrameLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelEditConsultationForm, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelFrameLayout.setVerticalGroup(
            jPanelFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFrameLayout.createSequentialGroup()
                .add(jPanelEditConsultationTittle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelEditConsultationForm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFrame, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFrame, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditConsultationUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditConsultationUpdateActionPerformed
        try {
            ControllerConsultation.editConsultation(this.consultationId,this.getCurrentConsultationDateTime(),this.getCurrentConsultationComment(),this.treatmentId,this.getCurrentSelectedVetId());
            ControllerConsultation.showDataTableAll(this.frame.getTableComponentsCollection(),this.frame.getTableComponentsConsultations());
            this.showSeeConsultationOnDispose = true;
            this.dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println(ex);
            javax.swing.JOptionPane.showMessageDialog(this.frame,ex);
        }
    }//GEN-LAST:event_jButtonEditConsultationUpdateActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            if(showSeeConsultationOnDispose) {
                ControllerConsultation.showSeeConsultationJDialogFromConsultationId(this.frame, this.consultationId);
            }
        } catch (Exception ex) {
            System.out.println(ex);
            javax.swing.JOptionPane.showMessageDialog(this.frame, ex);
        }
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditConsultationNewExam;
    private javax.swing.JButton jButtonEditConsultationUpdate;
    private javax.swing.JComboBox<String> jComboBoxNewConsultationVet;
    private javax.swing.JFormattedTextField jFormattedTextFieldEditConsultationDate;
    private javax.swing.JFormattedTextField jFormattedTextFieldEditConsultationTime;
    private javax.swing.JLabel jLabelEditConsultationAnimalName;
    private javax.swing.JLabel jLabelEditConsultationClientName;
    private javax.swing.JLabel jLabelEditConsultationComment;
    private javax.swing.JLabel jLabelEditConsultationDate;
    private javax.swing.JLabel jLabelEditConsultationTime;
    private javax.swing.JLabel jLabelEditConsultationTreatmentName;
    private javax.swing.JLabel jLabelEditConsultationVetName;
    private javax.swing.JLabel jLabelNewTreatmentTittle;
    private javax.swing.JPanel jPanelEditConsultationForm;
    private javax.swing.JPanel jPanelEditConsultationTittle;
    private javax.swing.JPanel jPanelFrame;
    private javax.swing.JScrollPane jScrollPaneEditConsultationComment;
    private javax.swing.JTextArea jTextAreaEditConsultationComment;
    private javax.swing.JTextField jTextFieldEditConsultationAnimalName;
    private javax.swing.JTextField jTextFieldEditConsultationClientName;
    private javax.swing.JTextField jTextFieldEditConsultationTreatmentName;
    // End of variables declaration//GEN-END:variables

}
