/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.Consultation;

import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import javax.swing.ComboBoxModel;

import Controller.ControllerConsultation;
import Controller.ControllerTreatment;

import View.MainJFrame;
import View.Vet.VetsComboModel;

/**
 *
 * @author mateu
 */
public class NewConsultationJDialog extends javax.swing.JDialog {

    private final MainJFrame frame;
    private final int treatmentId;
    private final String treatmentName;
    private final int animalId;
    private final String animalName;
    private final int clientId;
    private final String clientName;
    private ComboBoxModel vetsComboModel;
    private boolean showSeeTreatment = true;
    
    /** Creates new form NewConsultationJDialog */
    public NewConsultationJDialog(MainJFrame frame, boolean modal, int treatmentId, String treatmentName, int animalId, String animalName, int clientId, String clientName) throws SQLException, Exception {
        super(frame, modal);
        this.frame = frame;
        this.treatmentId = treatmentId;
        this.treatmentName = treatmentName;
        this.animalId = animalId;
        this.animalName = animalName;
        this.clientId = clientId;
        this.clientName = clientName;
        this.vetsComboModel = ControllerConsultation.getVetsComboModel();
        initComponents();
    }
    
    private LocalDate getCurrentConsultationDate() {
        return LocalDate.parse(jFormattedTextFieldNewConsultationDate.getText());
    }
    
    private LocalTime getCurrentConsultationTime() {
        return LocalTime.parse(jFormattedTextFieldNewConsultationTime.getText());
    }
    
    private LocalDateTime getCurrentConsultationDateTime() {
        return LocalDateTime.of(getCurrentConsultationDate(),getCurrentConsultationTime());
    }
    
    private String getCurrentConsultationComment() {
        return jTextAreaNewConsultationComment.getText();
    }
    
    private String getCurrentSelectedVet() {
        return (String) this.vetsComboModel.getSelectedItem();
    }
    
    private int getCurrentSelectedVetId() {
        return ControllerConsultation.getComboModelSelectedVetId(this.vetsComboModel,this.getCurrentSelectedVet());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFrame = new javax.swing.JPanel();
        jPanelNewConsultationTittle = new javax.swing.JPanel();
        jLabelNewTreatmentTittle = new javax.swing.JLabel();
        jPanelNewConsultationForm = new javax.swing.JPanel();
        jLabelNewConsultationDate = new javax.swing.JLabel();
        jFormattedTextFieldNewConsultationDate = new javax.swing.JFormattedTextField();
        jLabelNewConsultationTime = new javax.swing.JLabel();
        jFormattedTextFieldNewConsultationTime = new javax.swing.JFormattedTextField();
        jLabelNewConsultationTreatmentName = new javax.swing.JLabel();
        jTextFieldNewConsultationTreatmentName = new javax.swing.JTextField();
        jLabelNewConsultationAnimalName = new javax.swing.JLabel();
        jTextFieldNewConsultationAnimalName = new javax.swing.JTextField();
        jLabelNewConsultationVetName = new javax.swing.JLabel();
        jLabelNewConsultationClientName = new javax.swing.JLabel();
        jTextFieldNewConsultationClientName = new javax.swing.JTextField();
        jComboBoxNewConsultationVet = new javax.swing.JComboBox<>();
        jLabelNewConsultationComment = new javax.swing.JLabel();
        jScrollPaneNewConsultationComment = new javax.swing.JScrollPane();
        jTextAreaNewConsultationComment = new javax.swing.JTextArea();
        jButtonNewConsultationConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Consultation");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanelNewConsultationTittle.setLayout(new java.awt.BorderLayout());

        jLabelNewTreatmentTittle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelNewTreatmentTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNewTreatmentTittle.setText("New Consultation");
        jPanelNewConsultationTittle.add(jLabelNewTreatmentTittle, java.awt.BorderLayout.CENTER);

        jLabelNewConsultationDate.setText("Date");

        try {
            jFormattedTextFieldNewConsultationDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldNewConsultationDate.setText("");

        jLabelNewConsultationTime.setText("Hour");

        try {
            jFormattedTextFieldNewConsultationTime.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelNewConsultationTreatmentName.setText("Treatment");

        jTextFieldNewConsultationTreatmentName.setEditable(false);
        jTextFieldNewConsultationTreatmentName.setText(this.treatmentName);
        jTextFieldNewConsultationTreatmentName.setDisabledTextColor(java.awt.Color.black);
        jTextFieldNewConsultationTreatmentName.setEnabled(false);

        jLabelNewConsultationAnimalName.setText("Animal");

        jTextFieldNewConsultationAnimalName.setEditable(false);
        jTextFieldNewConsultationAnimalName.setText(this.animalName);
        jTextFieldNewConsultationAnimalName.setDisabledTextColor(java.awt.Color.black);
        jTextFieldNewConsultationAnimalName.setEnabled(false);

        jLabelNewConsultationVetName.setText("Vet");

        jLabelNewConsultationClientName.setText("Client");

        jTextFieldNewConsultationClientName.setEditable(false);
        jTextFieldNewConsultationClientName.setText(this.clientName);
        jTextFieldNewConsultationClientName.setDisabledTextColor(java.awt.Color.black);
        jTextFieldNewConsultationClientName.setEnabled(false);

        jComboBoxNewConsultationVet.setModel(this.vetsComboModel);
        jComboBoxNewConsultationVet.setToolTipText("");
        jComboBoxNewConsultationVet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxNewConsultationVet.setEnabled(!ControllerConsultation.isVetsComboModelEmpty(this.vetsComboModel));

        jLabelNewConsultationComment.setText("Comment");

        jTextAreaNewConsultationComment.setColumns(20);
        jTextAreaNewConsultationComment.setRows(5);
        jScrollPaneNewConsultationComment.setViewportView(jTextAreaNewConsultationComment);

        jButtonNewConsultationConfirm.setText("Register");
        jButtonNewConsultationConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNewConsultationConfirm.setEnabled(!ControllerConsultation.isVetsComboModelEmpty(this.vetsComboModel));
        jButtonNewConsultationConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewConsultationConfirmActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelNewConsultationFormLayout = new org.jdesktop.layout.GroupLayout(jPanelNewConsultationForm);
        jPanelNewConsultationForm.setLayout(jPanelNewConsultationFormLayout);
        jPanelNewConsultationFormLayout.setHorizontalGroup(
            jPanelNewConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelNewConsultationFormLayout.createSequentialGroup()
                .add(jPanelNewConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabelNewConsultationTime, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabelNewConsultationDate, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabelNewConsultationTreatmentName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabelNewConsultationAnimalName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabelNewConsultationClientName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabelNewConsultationComment, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jFormattedTextFieldNewConsultationDate)
                    .add(jFormattedTextFieldNewConsultationTime)
                    .add(jScrollPaneNewConsultationComment)
                    .add(jTextFieldNewConsultationTreatmentName)
                    .add(jTextFieldNewConsultationAnimalName)
                    .add(jTextFieldNewConsultationClientName)))
            .add(jPanelNewConsultationFormLayout.createSequentialGroup()
                .add(jLabelNewConsultationVetName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jComboBoxNewConsultationVet, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelNewConsultationFormLayout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .add(jButtonNewConsultationConfirm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 83, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(145, 145, 145))
        );
        jPanelNewConsultationFormLayout.setVerticalGroup(
            jPanelNewConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelNewConsultationFormLayout.createSequentialGroup()
                .add(jPanelNewConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jFormattedTextFieldNewConsultationDate)
                    .add(jLabelNewConsultationDate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jFormattedTextFieldNewConsultationTime)
                    .add(jLabelNewConsultationTime, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelNewConsultationTreatmentName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldNewConsultationTreatmentName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldNewConsultationAnimalName)
                    .add(jLabelNewConsultationAnimalName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldNewConsultationClientName)
                    .add(jLabelNewConsultationClientName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelNewConsultationVetName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jComboBoxNewConsultationVet, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPaneNewConsultationComment, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelNewConsultationComment))
                .add(59, 59, 59)
                .add(jButtonNewConsultationConfirm))
        );

        org.jdesktop.layout.GroupLayout jPanelFrameLayout = new org.jdesktop.layout.GroupLayout(jPanelFrame);
        jPanelFrame.setLayout(jPanelFrameLayout);
        jPanelFrameLayout.setHorizontalGroup(
            jPanelFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelNewConsultationTittle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFrameLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelNewConsultationForm, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelFrameLayout.setVerticalGroup(
            jPanelFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFrameLayout.createSequentialGroup()
                .add(jPanelNewConsultationTittle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewConsultationForm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFrame, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFrame, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewConsultationConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewConsultationConfirmActionPerformed
        try {
            ControllerConsultation.newConsultation(this.getCurrentConsultationDateTime(),this.getCurrentConsultationComment(),this.treatmentId,this.getCurrentSelectedVetId());
            ControllerConsultation.showDataTableAll(this.frame.getTableComponentsCollection(),this.frame.getTableComponentsConsultations());
            this.showSeeTreatment = false;
            this.dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println(ex);
            javax.swing.JOptionPane.showMessageDialog(this.frame,ex);
        }
    }//GEN-LAST:event_jButtonNewConsultationConfirmActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            if(showSeeTreatment)
                ControllerTreatment.showSeeTreatmentJDialogFromTreatmentId(this.frame, this.treatmentId);
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println(ex);
            javax.swing.JOptionPane.showMessageDialog(this.frame, ex);
        }
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNewConsultationConfirm;
    private javax.swing.JComboBox<String> jComboBoxNewConsultationVet;
    private javax.swing.JFormattedTextField jFormattedTextFieldNewConsultationDate;
    private javax.swing.JFormattedTextField jFormattedTextFieldNewConsultationTime;
    private javax.swing.JLabel jLabelNewConsultationAnimalName;
    private javax.swing.JLabel jLabelNewConsultationClientName;
    private javax.swing.JLabel jLabelNewConsultationComment;
    private javax.swing.JLabel jLabelNewConsultationDate;
    private javax.swing.JLabel jLabelNewConsultationTime;
    private javax.swing.JLabel jLabelNewConsultationTreatmentName;
    private javax.swing.JLabel jLabelNewConsultationVetName;
    private javax.swing.JLabel jLabelNewTreatmentTittle;
    private javax.swing.JPanel jPanelFrame;
    private javax.swing.JPanel jPanelNewConsultationForm;
    private javax.swing.JPanel jPanelNewConsultationTittle;
    private javax.swing.JScrollPane jScrollPaneNewConsultationComment;
    private javax.swing.JTextArea jTextAreaNewConsultationComment;
    private javax.swing.JTextField jTextFieldNewConsultationAnimalName;
    private javax.swing.JTextField jTextFieldNewConsultationClientName;
    private javax.swing.JTextField jTextFieldNewConsultationTreatmentName;
    // End of variables declaration//GEN-END:variables

}
