/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.Consultation;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;

import Controller.ControllerAnimal;
import Controller.ControllerClient;
import Controller.ControllerConsultation;
import Controller.ControllerExam;
import Controller.ControllerTreatment;
import Controller.ControllerVet;

import View.MainJFrame;

/**
 *
 * @author mateu
 */
public class SeeConsultationJDialog extends javax.swing.JDialog {

    private final MainJFrame frame;
    private final int consultationId;
    private final LocalDateTime consultationLocalDateTime;
    private final String consultationComment;
    private final int treatmentId;
    private final String treatmentName;
    private final int animalId;
    private final String animalName;
    private final int clientId;
    private final String clientName;
    private final int vetId;
    private final String vetName;
    
    /** Creates new form SeeConsultationJDialog */
    public SeeConsultationJDialog(MainJFrame frame, boolean modal, int consultationId, LocalDateTime consultationLocalDateTime, String consultationComment, int treatmentId, String treatmentName, int animalId, String animalName, int clientId, String clientName, int vetId, String vetName) {
        super(frame, modal);
        this.frame = frame;
        this.consultationId = consultationId;
        this.consultationLocalDateTime = consultationLocalDateTime;
        this.consultationComment = consultationComment;
        this.treatmentId = treatmentId;
        this.treatmentName = treatmentName;
        this.animalId = animalId;
        this.animalName = animalName;
        this.clientId = clientId;
        this.clientName = clientName;
        this.vetId = vetId;
        this.vetName = vetName;
        initComponents();
    }
    
    public LocalDate getConsultationDate() {
        return LocalDate.of(this.consultationLocalDateTime.getYear(), this.consultationLocalDateTime.getMonth(), this.consultationLocalDateTime.getDayOfMonth());
    }
    
    public LocalTime getConsultationTime() {
        return LocalTime.of(this.consultationLocalDateTime.getHour(), this.consultationLocalDateTime.getMinute());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFrame = new javax.swing.JPanel();
        jPanelEditConsultationTittle = new javax.swing.JPanel();
        jLabelSeeConsultationTittle = new javax.swing.JLabel();
        jPanelSeeConsultationActionButtons = new javax.swing.JPanel();
        jButtonSeeConsultationEdit = new javax.swing.JButton();
        jButtonSeeConsultationDelete = new javax.swing.JButton();
        jPanelSeeConsultationForm = new javax.swing.JPanel();
        jLabelSeeConsultationDate = new javax.swing.JLabel();
        jTextFieldSeeConsultationDate = new javax.swing.JFormattedTextField();
        jLabelSeeConsultationTime = new javax.swing.JLabel();
        jTextFieldSeeConsultationTime = new javax.swing.JFormattedTextField();
        jLabelSeeConsulltationTreatmentName = new javax.swing.JLabel();
        jTextFieldSeeConsultationTreatmentName = new javax.swing.JTextField();
        jButtonSeeConsultationSeeTreatment = new javax.swing.JButton();
        jLabelSeeConsultationAnimalName = new javax.swing.JLabel();
        jTextFieldSeeConsultationAnimalName = new javax.swing.JTextField();
        jButtonSeeConsultationSeeAnimal = new javax.swing.JButton();
        jLabelSeeConsultationClientName = new javax.swing.JLabel();
        jTextFieldSeeConsultationClientName = new javax.swing.JTextField();
        jButtonSeeConsultationSeeClient = new javax.swing.JButton();
        jLabelSeeConsultationVetName = new javax.swing.JLabel();
        jTextFieldSeeConsultationVetName = new javax.swing.JTextField();
        jButtonSeeConsultationSeeVet = new javax.swing.JButton();
        jLabelSeeConsultationComment = new javax.swing.JLabel();
        jScrollPaneSeeConsultationComment = new javax.swing.JScrollPane();
        jTextAreaSeeConsultationComment = new javax.swing.JTextArea();
        jButtonSeeConsultationSeeExams = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("See Consultation");
        setResizable(false);

        jPanelEditConsultationTittle.setLayout(new java.awt.BorderLayout());

        jLabelSeeConsultationTittle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelSeeConsultationTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSeeConsultationTittle.setText("See Consultation");
        jPanelEditConsultationTittle.add(jLabelSeeConsultationTittle, java.awt.BorderLayout.CENTER);

        jPanelSeeConsultationActionButtons.setPreferredSize(new java.awt.Dimension(120, 50));

        jButtonSeeConsultationEdit.setText("Edit");
        jButtonSeeConsultationEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSeeConsultationEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeeConsultationEditActionPerformed(evt);
            }
        });

        jButtonSeeConsultationDelete.setText("Delete");
        jButtonSeeConsultationDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSeeConsultationDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeeConsultationDeleteActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelSeeConsultationActionButtonsLayout = new org.jdesktop.layout.GroupLayout(jPanelSeeConsultationActionButtons);
        jPanelSeeConsultationActionButtons.setLayout(jPanelSeeConsultationActionButtonsLayout);
        jPanelSeeConsultationActionButtonsLayout.setHorizontalGroup(
            jPanelSeeConsultationActionButtonsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelSeeConsultationActionButtonsLayout.createSequentialGroup()
                .add(jButtonSeeConsultationEdit)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonSeeConsultationDelete)
                .add(0, 0, Short.MAX_VALUE))
        );
        jPanelSeeConsultationActionButtonsLayout.setVerticalGroup(
            jPanelSeeConsultationActionButtonsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelSeeConsultationActionButtonsLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .add(jPanelSeeConsultationActionButtonsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonSeeConsultationEdit)
                    .add(jButtonSeeConsultationDelete))
                .addContainerGap())
        );

        jPanelEditConsultationTittle.add(jPanelSeeConsultationActionButtons, java.awt.BorderLayout.LINE_END);

        jLabelSeeConsultationDate.setText("Date");

        jTextFieldSeeConsultationDate.setEditable(false);
        try {
            jTextFieldSeeConsultationDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldSeeConsultationDate.setText(this.getConsultationDate().toString());
        jTextFieldSeeConsultationDate.setDisabledTextColor(java.awt.Color.black);
        jTextFieldSeeConsultationDate.setEnabled(false);

        jLabelSeeConsultationTime.setText("Hour");

        jTextFieldSeeConsultationTime.setEditable(false);
        try {
            jTextFieldSeeConsultationTime.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldSeeConsultationTime.setText(this.getConsultationTime().toString());
        jTextFieldSeeConsultationTime.setDisabledTextColor(java.awt.Color.black);
        jTextFieldSeeConsultationTime.setEnabled(false);

        jLabelSeeConsulltationTreatmentName.setText("Treatment");

        jTextFieldSeeConsultationTreatmentName.setEditable(false);
        jTextFieldSeeConsultationTreatmentName.setText(this.treatmentName);
        jTextFieldSeeConsultationTreatmentName.setDisabledTextColor(java.awt.Color.black);
        jTextFieldSeeConsultationTreatmentName.setEnabled(false);

        jButtonSeeConsultationSeeTreatment.setText("See Treatment");
        jButtonSeeConsultationSeeTreatment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSeeConsultationSeeTreatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeeConsultationSeeTreatmentActionPerformed(evt);
            }
        });

        jLabelSeeConsultationAnimalName.setText("Animal");

        jTextFieldSeeConsultationAnimalName.setEditable(false);
        jTextFieldSeeConsultationAnimalName.setText(this.animalName);
        jTextFieldSeeConsultationAnimalName.setDisabledTextColor(java.awt.Color.black);
        jTextFieldSeeConsultationAnimalName.setEnabled(false);

        jButtonSeeConsultationSeeAnimal.setText("See Animal");
        jButtonSeeConsultationSeeAnimal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSeeConsultationSeeAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeeConsultationSeeAnimalActionPerformed(evt);
            }
        });

        jLabelSeeConsultationClientName.setText("Client");

        jTextFieldSeeConsultationClientName.setEditable(false);
        jTextFieldSeeConsultationClientName.setText(this.clientName);
        jTextFieldSeeConsultationClientName.setDisabledTextColor(java.awt.Color.black);
        jTextFieldSeeConsultationClientName.setEnabled(false);

        jButtonSeeConsultationSeeClient.setText("See Client");
        jButtonSeeConsultationSeeClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSeeConsultationSeeClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeeConsultationSeeClientActionPerformed(evt);
            }
        });

        jLabelSeeConsultationVetName.setText("Vet");

        jTextFieldSeeConsultationVetName.setEditable(false);
        jTextFieldSeeConsultationVetName.setText(this.vetName);
        jTextFieldSeeConsultationVetName.setDisabledTextColor(java.awt.Color.black);
        jTextFieldSeeConsultationVetName.setEnabled(false);

        jButtonSeeConsultationSeeVet.setText("See Vet");
        jButtonSeeConsultationSeeVet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSeeConsultationSeeVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeeConsultationSeeVetActionPerformed(evt);
            }
        });

        jLabelSeeConsultationComment.setText("Comment");

        jTextAreaSeeConsultationComment.setEditable(false);
        jTextAreaSeeConsultationComment.setColumns(20);
        jTextAreaSeeConsultationComment.setRows(5);
        jTextAreaSeeConsultationComment.setText(this.consultationComment);
        jTextAreaSeeConsultationComment.setDisabledTextColor(java.awt.Color.black);
        jTextAreaSeeConsultationComment.setEnabled(false);
        jScrollPaneSeeConsultationComment.setViewportView(jTextAreaSeeConsultationComment);

        jButtonSeeConsultationSeeExams.setText("See Exams");
        jButtonSeeConsultationSeeExams.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSeeConsultationSeeExams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeeConsultationSeeExamsActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelSeeConsultationFormLayout = new org.jdesktop.layout.GroupLayout(jPanelSeeConsultationForm);
        jPanelSeeConsultationForm.setLayout(jPanelSeeConsultationFormLayout);
        jPanelSeeConsultationFormLayout.setHorizontalGroup(
            jPanelSeeConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelSeeConsultationFormLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButtonSeeConsultationSeeExams)
                .add(144, 144, 144))
            .add(jPanelSeeConsultationFormLayout.createSequentialGroup()
                .add(jPanelSeeConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(jLabelSeeConsultationVetName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabelSeeConsultationComment, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabelSeeConsultationTime, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabelSeeConsultationDate, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabelSeeConsulltationTreatmentName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabelSeeConsultationAnimalName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabelSeeConsultationClientName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelSeeConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTextFieldSeeConsultationDate)
                    .add(jTextFieldSeeConsultationTime)
                    .add(jPanelSeeConsultationFormLayout.createSequentialGroup()
                        .add(jScrollPaneSeeConsultationComment, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 325, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 10, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelSeeConsultationFormLayout.createSequentialGroup()
                        .add(jPanelSeeConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTextFieldSeeConsultationClientName)
                            .add(jTextFieldSeeConsultationAnimalName)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextFieldSeeConsultationTreatmentName)
                            .add(jTextFieldSeeConsultationVetName))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanelSeeConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jButtonSeeConsultationSeeTreatment, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jButtonSeeConsultationSeeAnimal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jButtonSeeConsultationSeeClient, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jButtonSeeConsultationSeeVet, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanelSeeConsultationFormLayout.setVerticalGroup(
            jPanelSeeConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelSeeConsultationFormLayout.createSequentialGroup()
                .add(jPanelSeeConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jTextFieldSeeConsultationDate)
                    .add(jLabelSeeConsultationDate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelSeeConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jTextFieldSeeConsultationTime)
                    .add(jLabelSeeConsultationTime, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelSeeConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelSeeConsulltationTreatmentName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldSeeConsultationTreatmentName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonSeeConsultationSeeTreatment, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelSeeConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanelSeeConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jTextFieldSeeConsultationAnimalName)
                        .add(jButtonSeeConsultationSeeAnimal))
                    .add(jLabelSeeConsultationAnimalName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelSeeConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanelSeeConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jTextFieldSeeConsultationClientName)
                        .add(jButtonSeeConsultationSeeClient))
                    .add(jLabelSeeConsultationClientName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelSeeConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelSeeConsultationVetName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldSeeConsultationVetName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonSeeConsultationSeeVet))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelSeeConsultationFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelSeeConsultationFormLayout.createSequentialGroup()
                        .add(jLabelSeeConsultationComment, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(112, 112, 112))
                    .add(jPanelSeeConsultationFormLayout.createSequentialGroup()
                        .add(jScrollPaneSeeConsultationComment, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .add(jButtonSeeConsultationSeeExams))
        );

        org.jdesktop.layout.GroupLayout jPanelFrameLayout = new org.jdesktop.layout.GroupLayout(jPanelFrame);
        jPanelFrame.setLayout(jPanelFrameLayout);
        jPanelFrameLayout.setHorizontalGroup(
            jPanelFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFrameLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelSeeConsultationForm, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFrameLayout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(jPanelEditConsultationTittle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 345, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPanelFrameLayout.setVerticalGroup(
            jPanelFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFrameLayout.createSequentialGroup()
                .add(jPanelEditConsultationTittle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelSeeConsultationForm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFrame, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFrame, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSeeConsultationEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeeConsultationEditActionPerformed
        try {
            this.dispose();
            ControllerConsultation.showEditConsultationJDialogFromConsultationId(this.frame, this.consultationId);
        } catch (Exception ex) {
            System.out.println(ex);
            javax.swing.JOptionPane.showMessageDialog(this.frame, ex);
        }
    }//GEN-LAST:event_jButtonSeeConsultationEditActionPerformed

    private void jButtonSeeConsultationDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeeConsultationDeleteActionPerformed
        try {
            this.dispose();
            ControllerConsultation.showDeleteConsultationJDialogFromConsultationId(this.frame, this.consultationId);
        } catch (Exception ex) {
            System.out.println(ex);
            javax.swing.JOptionPane.showMessageDialog(this.frame, ex);
        }
    }//GEN-LAST:event_jButtonSeeConsultationDeleteActionPerformed

    private void jButtonSeeConsultationSeeTreatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeeConsultationSeeTreatmentActionPerformed
        try {
            ControllerTreatment.showSeeTreatmentJDialogFromTreatmentId(this.frame,this.treatmentId);
        } catch (Exception ex) {
            System.out.println(ex);
            javax.swing.JOptionPane.showMessageDialog(this.frame,ex);
        }
    }//GEN-LAST:event_jButtonSeeConsultationSeeTreatmentActionPerformed

    private void jButtonSeeConsultationSeeAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeeConsultationSeeAnimalActionPerformed
        try {
            ControllerAnimal.showSeeAnimalJDialogFromAnimalId(this.frame,this.animalId);
        } catch (Exception ex) {
            System.out.println(ex);
            javax.swing.JOptionPane.showMessageDialog(this.frame,ex);
        }
    }//GEN-LAST:event_jButtonSeeConsultationSeeAnimalActionPerformed

    private void jButtonSeeConsultationSeeClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeeConsultationSeeClientActionPerformed
        try {
            ControllerClient.showSeeClientJDialogFromClientId(this.frame,this.clientId);
        } catch (Exception ex) {
            System.out.println(ex);
            javax.swing.JOptionPane.showMessageDialog(this.frame,ex);
        }
    }//GEN-LAST:event_jButtonSeeConsultationSeeClientActionPerformed

    private void jButtonSeeConsultationSeeVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeeConsultationSeeVetActionPerformed
        try {
            ControllerVet.showSeeVetJDialogFromVetId(this.frame,this.vetId);
        } catch (Exception ex) {
            System.out.println(ex);
            javax.swing.JOptionPane.showMessageDialog(this.frame,ex);
        }
    }//GEN-LAST:event_jButtonSeeConsultationSeeVetActionPerformed

    private void jButtonSeeConsultationSeeExamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeeConsultationSeeExamsActionPerformed
        try {
            ControllerExam.showDataTableByConsultationId(this.frame.getTableComponentsCollection(), this.frame.getTableComponentsExams(), this.consultationId);
        } catch (Exception ex) {
            System.out.println(ex);
            javax.swing.JOptionPane.showMessageDialog(this.frame, ex);
        }
    }//GEN-LAST:event_jButtonSeeConsultationSeeExamsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSeeConsultationDelete;
    private javax.swing.JButton jButtonSeeConsultationEdit;
    private javax.swing.JButton jButtonSeeConsultationSeeAnimal;
    private javax.swing.JButton jButtonSeeConsultationSeeClient;
    private javax.swing.JButton jButtonSeeConsultationSeeExams;
    private javax.swing.JButton jButtonSeeConsultationSeeTreatment;
    private javax.swing.JButton jButtonSeeConsultationSeeVet;
    private javax.swing.JLabel jLabelSeeConsulltationTreatmentName;
    private javax.swing.JLabel jLabelSeeConsultationAnimalName;
    private javax.swing.JLabel jLabelSeeConsultationClientName;
    private javax.swing.JLabel jLabelSeeConsultationComment;
    private javax.swing.JLabel jLabelSeeConsultationDate;
    private javax.swing.JLabel jLabelSeeConsultationTime;
    private javax.swing.JLabel jLabelSeeConsultationTittle;
    private javax.swing.JLabel jLabelSeeConsultationVetName;
    private javax.swing.JPanel jPanelEditConsultationTittle;
    private javax.swing.JPanel jPanelFrame;
    private javax.swing.JPanel jPanelSeeConsultationActionButtons;
    private javax.swing.JPanel jPanelSeeConsultationForm;
    private javax.swing.JScrollPane jScrollPaneSeeConsultationComment;
    private javax.swing.JTextArea jTextAreaSeeConsultationComment;
    private javax.swing.JTextField jTextFieldSeeConsultationAnimalName;
    private javax.swing.JTextField jTextFieldSeeConsultationClientName;
    private javax.swing.JFormattedTextField jTextFieldSeeConsultationDate;
    private javax.swing.JFormattedTextField jTextFieldSeeConsultationTime;
    private javax.swing.JTextField jTextFieldSeeConsultationTreatmentName;
    private javax.swing.JTextField jTextFieldSeeConsultationVetName;
    // End of variables declaration//GEN-END:variables

}
