/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.Animal;

import java.sql.SQLException;
import java.util.List;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;

import Controller.ControllerAnimal;
import Controller.ControllerTreatment;

/**
 *
 * @author mateu
 */
public class EditAnimalJDialog extends javax.swing.JDialog {

    private View.MainJFrame frame;
    private int animalId;
    private String animalName;
    private String animalBirthYear;
    private String animalGender;
    private int clientId;
    private String clientName;
    private int speciesId;
    private String speciesName;
    private ComboBoxModel genderComboModel;
    private ComboBoxModel speciesComboModel;
    
    /** Creates new form EditAnimalJDialog */
    public EditAnimalJDialog(View.MainJFrame frame, boolean modal, int animalId, String animalName, String animalBirthYear, String animalGender, int clientId, String clientName, int speciesId, String speciesName) throws SQLException, Exception {
        super(frame, modal);
        this.frame = frame;
        this.animalId = animalId;
        this.animalName = animalName;
        this.animalBirthYear = animalBirthYear;
        this.animalGender = animalGender;
        this.clientId = clientId;
        this.clientName = clientName;
        this.speciesId = speciesId;
        this.speciesName = speciesName;
        this.genderComboModel = ControllerAnimal.getGenderComboModel(this.animalGender);
        this.speciesComboModel = ControllerAnimal.getSpeciesComboModel(this.speciesName);
        initComponents();
        this.jPanelEditAnimalNewSpecies.setVisible(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFrame = new javax.swing.JPanel();
        jPanelEditAnimalTittle = new javax.swing.JPanel();
        jLabelNewAnimalTittle = new javax.swing.JLabel();
        jPanelEditAnimalForm = new javax.swing.JPanel();
        jLabelEditAnimalName = new javax.swing.JLabel();
        jTextFieldEditAnimalName = new javax.swing.JTextField();
        jLabelEditAnimalBirthYear = new javax.swing.JLabel();
        jFormattedTextFieldEditAnimalBirthYear = new javax.swing.JFormattedTextField();
        jLabelEditAnimalGender = new javax.swing.JLabel();
        jComboBoxEditAnimalGender = new javax.swing.JComboBox<>();
        jLabelEditAnimalSpecies = new javax.swing.JLabel();
        jComboBoxEditAnimalSpecies = new javax.swing.JComboBox<>();
        jPanelEditAnimalNewSpecies = new javax.swing.JPanel();
        jLabelNewAnimalNewSpeciesName = new javax.swing.JLabel();
        jTextFieldNewAnimalNewSpeciesName = new javax.swing.JTextField();
        jLabelEditAnimalClient = new javax.swing.JLabel();
        jTextFieldEditAnimalClientName = new javax.swing.JTextField();
        jButtonEditAnimalConfirm = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Animal");
        setResizable(false);

        jPanelEditAnimalTittle.setLayout(new java.awt.BorderLayout());

        jLabelNewAnimalTittle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelNewAnimalTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNewAnimalTittle.setText("Edit Animal");
        jPanelEditAnimalTittle.add(jLabelNewAnimalTittle, java.awt.BorderLayout.CENTER);

        jLabelEditAnimalName.setText("Name");

        jTextFieldEditAnimalName.setText(this.animalName);

        jLabelEditAnimalBirthYear.setText("Birth Year");

        try {
            jFormattedTextFieldEditAnimalBirthYear.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldEditAnimalBirthYear.setText(this.animalBirthYear);

        jLabelEditAnimalGender.setText("Gender");

        jComboBoxEditAnimalGender.setModel(this.genderComboModel);
        jComboBoxEditAnimalGender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelEditAnimalSpecies.setLabelFor(jComboBoxEditAnimalSpecies);
        jLabelEditAnimalSpecies.setText("Species");

        jComboBoxEditAnimalSpecies.setModel(this.speciesComboModel);
        jComboBoxEditAnimalSpecies.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxEditAnimalSpecies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEditAnimalSpeciesActionPerformed(evt);
            }
        });

        jLabelNewAnimalNewSpeciesName.setLabelFor(jTextFieldNewAnimalNewSpeciesName);
        jLabelNewAnimalNewSpeciesName.setText("New Species Name");

        org.jdesktop.layout.GroupLayout jPanelEditAnimalNewSpeciesLayout = new org.jdesktop.layout.GroupLayout(jPanelEditAnimalNewSpecies);
        jPanelEditAnimalNewSpecies.setLayout(jPanelEditAnimalNewSpeciesLayout);
        jPanelEditAnimalNewSpeciesLayout.setHorizontalGroup(
            jPanelEditAnimalNewSpeciesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelEditAnimalNewSpeciesLayout.createSequentialGroup()
                .add(jLabelNewAnimalNewSpeciesName)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextFieldNewAnimalNewSpeciesName))
        );
        jPanelEditAnimalNewSpeciesLayout.setVerticalGroup(
            jPanelEditAnimalNewSpeciesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelEditAnimalNewSpeciesLayout.createSequentialGroup()
                .add(jTextFieldNewAnimalNewSpeciesName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
            .add(jLabelNewAnimalNewSpeciesName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabelEditAnimalClient.setLabelFor(jTextFieldEditAnimalClientName);
        jLabelEditAnimalClient.setText("Client");
        jLabelEditAnimalClient.setMaximumSize(new java.awt.Dimension(36, 14));
        jLabelEditAnimalClient.setMinimumSize(new java.awt.Dimension(36, 14));
        jLabelEditAnimalClient.setPreferredSize(new java.awt.Dimension(36, 14));

        jTextFieldEditAnimalClientName.setEditable(false);
        jTextFieldEditAnimalClientName.setText(this.clientName);
        jTextFieldEditAnimalClientName.setToolTipText("");
        jTextFieldEditAnimalClientName.setDisabledTextColor(java.awt.Color.black);
        jTextFieldEditAnimalClientName.setEnabled(false);
        jTextFieldEditAnimalClientName.setMaximumSize(new java.awt.Dimension(101, 20));
        jTextFieldEditAnimalClientName.setMinimumSize(new java.awt.Dimension(101, 20));
        jTextFieldEditAnimalClientName.setPreferredSize(new java.awt.Dimension(101, 20));

        jButtonEditAnimalConfirm.setText("Update");
        jButtonEditAnimalConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton1.setText("New Treatment");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelEditAnimalFormLayout = new org.jdesktop.layout.GroupLayout(jPanelEditAnimalForm);
        jPanelEditAnimalForm.setLayout(jPanelEditAnimalFormLayout);
        jPanelEditAnimalFormLayout.setHorizontalGroup(
            jPanelEditAnimalFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelEditAnimalFormLayout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(jLabelEditAnimalName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextFieldEditAnimalName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 326, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(jPanelEditAnimalFormLayout.createSequentialGroup()
                .add(jPanelEditAnimalFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabelEditAnimalGender, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabelEditAnimalBirthYear, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabelEditAnimalSpecies, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(7, 7, 7)
                .add(jPanelEditAnimalFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jComboBoxEditAnimalGender, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jFormattedTextFieldEditAnimalBirthYear)
                    .add(jComboBoxEditAnimalSpecies, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .add(jPanelEditAnimalNewSpecies, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanelEditAnimalFormLayout.createSequentialGroup()
                .add(jLabelEditAnimalClient, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jTextFieldEditAnimalClientName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(jPanelEditAnimalFormLayout.createSequentialGroup()
                .add(137, 137, 137)
                .add(jButton1)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelEditAnimalFormLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButtonEditAnimalConfirm)
                .add(155, 155, 155))
        );
        jPanelEditAnimalFormLayout.setVerticalGroup(
            jPanelEditAnimalFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelEditAnimalFormLayout.createSequentialGroup()
                .add(jPanelEditAnimalFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelEditAnimalName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldEditAnimalName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelEditAnimalFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelEditAnimalBirthYear, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jFormattedTextFieldEditAnimalBirthYear, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelEditAnimalFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelEditAnimalGender)
                    .add(jComboBoxEditAnimalGender, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(9, 9, 9)
                .add(jPanelEditAnimalFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelEditAnimalSpecies, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jComboBoxEditAnimalSpecies, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelEditAnimalNewSpecies, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelEditAnimalFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabelEditAnimalClient, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jTextFieldEditAnimalClientName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButtonEditAnimalConfirm))
        );

        org.jdesktop.layout.GroupLayout jPanelFrameLayout = new org.jdesktop.layout.GroupLayout(jPanelFrame);
        jPanelFrame.setLayout(jPanelFrameLayout);
        jPanelFrameLayout.setHorizontalGroup(
            jPanelFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelEditAnimalTittle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFrameLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelEditAnimalForm, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelFrameLayout.setVerticalGroup(
            jPanelFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFrameLayout.createSequentialGroup()
                .add(jPanelEditAnimalTittle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelEditAnimalForm, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFrame, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFrame, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxEditAnimalSpeciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEditAnimalSpeciesActionPerformed
        this.jPanelEditAnimalNewSpecies.setVisible(this.jComboBoxEditAnimalSpecies.getSelectedItem().toString() == "Other");
    }//GEN-LAST:event_jComboBoxEditAnimalSpeciesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            ControllerTreatment.showNewTreatmentJDialogByAnimalId(this.frame,this.animalId);
        } catch (Exception ex) {
            System.out.println(ex);
            javax.swing.JOptionPane.showMessageDialog(this.frame,ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEditAnimalConfirm;
    private javax.swing.JComboBox<String> jComboBoxEditAnimalGender;
    private javax.swing.JComboBox<String> jComboBoxEditAnimalSpecies;
    private javax.swing.JFormattedTextField jFormattedTextFieldEditAnimalBirthYear;
    private javax.swing.JLabel jLabelEditAnimalBirthYear;
    private javax.swing.JLabel jLabelEditAnimalClient;
    private javax.swing.JLabel jLabelEditAnimalGender;
    private javax.swing.JLabel jLabelEditAnimalName;
    private javax.swing.JLabel jLabelEditAnimalSpecies;
    private javax.swing.JLabel jLabelNewAnimalNewSpeciesName;
    private javax.swing.JLabel jLabelNewAnimalTittle;
    private javax.swing.JPanel jPanelEditAnimalForm;
    private javax.swing.JPanel jPanelEditAnimalNewSpecies;
    private javax.swing.JPanel jPanelEditAnimalTittle;
    private javax.swing.JPanel jPanelFrame;
    private javax.swing.JTextField jTextFieldEditAnimalClientName;
    private javax.swing.JTextField jTextFieldEditAnimalName;
    private javax.swing.JTextField jTextFieldNewAnimalNewSpeciesName;
    // End of variables declaration//GEN-END:variables

}
