/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.Exam;

import View.MainJFrame;

/**
 *
 * @author mateu
 */
public class EditExamJDialog extends javax.swing.JDialog {

    private final MainJFrame frame;
    private final int examId;
    private final String examName;
    private final int treatmentId;
    private final String treatmentName;
    private final int consultationId;
    private final String consultationComment;
    private final int animalId;
    private final String animalName;
    private final int clientId;
    private final String clientName;
    private final int vetId;
    private final String vetName;
    
    /** Creates new form SeeExamJDialog */
    public EditExamJDialog(MainJFrame frame, boolean modal, int examId, String examName, int treatmentId, String treatmentName, int consultationId, String consultationComment, int animalId, String animalName, int clientId, String clientName, int vetId, String vetName) {
        super(frame, modal);
        this.frame = frame;
        this.examId = examId;
        this.examName = examName;
        this.treatmentId = treatmentId;
        this.treatmentName = treatmentName;
        this.consultationId = consultationId;
        this.consultationComment = consultationComment;
        this.animalId = animalId;
        this.animalName = animalName;
        this.clientId = clientId;
        this.clientName = clientName;
        this.vetId = vetId;
        this.vetName = vetName;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFrame = new javax.swing.JPanel();
        jPanelEditExamTittle = new javax.swing.JPanel();
        jLabelEditExamTittle = new javax.swing.JLabel();
        jPanelEditExamForm = new javax.swing.JPanel();
        jLabelEditExamName = new javax.swing.JLabel();
        jTextFieldEditExamName = new javax.swing.JTextField();
        jButtonEditExamSelectConsultation = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPaneEditExamConsultationComment = new javax.swing.JScrollPane();
        jTextAreaEditExamConsultationComment = new javax.swing.JTextArea();
        jButtonEditExamConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Exam");
        setResizable(false);

        jPanelEditExamTittle.setLayout(new java.awt.BorderLayout());

        jLabelEditExamTittle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelEditExamTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEditExamTittle.setText("Edit Exam");
        jPanelEditExamTittle.add(jLabelEditExamTittle, java.awt.BorderLayout.CENTER);

        jLabelEditExamName.setText("Name");

        jTextFieldEditExamName.setText("Exam1");

        jButtonEditExamSelectConsultation.setText("Select Consultation");
        jButtonEditExamSelectConsultation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setText("Treatment");

        jTextField2.setEditable(false);
        jTextField2.setText("Treatment1");
        jTextField2.setDisabledTextColor(java.awt.Color.black);
        jTextField2.setEnabled(false);

        jLabel5.setText("Vet");

        jTextField3.setEditable(false);
        jTextField3.setText("Vet1");
        jTextField3.setDisabledTextColor(java.awt.Color.black);
        jTextField3.setEnabled(false);

        jLabel6.setText("Animal");

        jTextField4.setEditable(false);
        jTextField4.setText("Foguinho");
        jTextField4.setDisabledTextColor(java.awt.Color.black);
        jTextField4.setEnabled(false);

        jLabel7.setText("Client");

        jTextField5.setEditable(false);
        jTextField5.setText("Jenisvaldo");
        jTextField5.setDisabledTextColor(java.awt.Color.black);
        jTextField5.setEnabled(false);

        jLabel1.setText("Consultation Comments");

        jTextAreaEditExamConsultationComment.setEditable(false);
        jTextAreaEditExamConsultationComment.setColumns(20);
        jTextAreaEditExamConsultationComment.setRows(5);
        jTextAreaEditExamConsultationComment.setText("Consultation 1 - Treatment 1 - Vet 1");
        jTextAreaEditExamConsultationComment.setDisabledTextColor(java.awt.Color.black);
        jTextAreaEditExamConsultationComment.setEnabled(false);
        jScrollPaneEditExamConsultationComment.setViewportView(jTextAreaEditExamConsultationComment);

        jButtonEditExamConfirm.setText("Update");
        jButtonEditExamConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        org.jdesktop.layout.GroupLayout jPanelEditExamFormLayout = new org.jdesktop.layout.GroupLayout(jPanelEditExamForm);
        jPanelEditExamForm.setLayout(jPanelEditExamFormLayout);
        jPanelEditExamFormLayout.setHorizontalGroup(
            jPanelEditExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelEditExamFormLayout.createSequentialGroup()
                .add(jLabelEditExamName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(4, 4, 4)
                .add(jTextFieldEditExamName))
            .add(jPanelEditExamFormLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPaneEditExamConsultationComment, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelEditExamFormLayout.createSequentialGroup()
                .add(jLabel1)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(jPanelEditExamFormLayout.createSequentialGroup()
                .add(jPanelEditExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(jPanelEditExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelEditExamFormLayout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(jTextField3))
                    .add(jPanelEditExamFormLayout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(jTextField4))
                    .add(jPanelEditExamFormLayout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(jTextField5))
                    .add(jPanelEditExamFormLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextField2))))
            .add(jPanelEditExamFormLayout.createSequentialGroup()
                .add(jPanelEditExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelEditExamFormLayout.createSequentialGroup()
                        .add(127, 127, 127)
                        .add(jButtonEditExamSelectConsultation))
                    .add(jPanelEditExamFormLayout.createSequentialGroup()
                        .add(154, 154, 154)
                        .add(jButtonEditExamConfirm)))
                .add(0, 0, Short.MAX_VALUE))
        );
        jPanelEditExamFormLayout.setVerticalGroup(
            jPanelEditExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelEditExamFormLayout.createSequentialGroup()
                .add(jPanelEditExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelEditExamName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldEditExamName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonEditExamSelectConsultation)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelEditExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelEditExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(9, 9, 9)
                .add(jPanelEditExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelEditExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPaneEditExamConsultationComment, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButtonEditExamConfirm))
        );

        org.jdesktop.layout.GroupLayout jPanelFrameLayout = new org.jdesktop.layout.GroupLayout(jPanelFrame);
        jPanelFrame.setLayout(jPanelFrameLayout);
        jPanelFrameLayout.setHorizontalGroup(
            jPanelFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelEditExamTittle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFrameLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelEditExamForm, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelFrameLayout.setVerticalGroup(
            jPanelFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFrameLayout.createSequentialGroup()
                .add(jPanelEditExamTittle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelEditExamForm, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFrame, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFrame, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditExamConfirm;
    private javax.swing.JButton jButtonEditExamSelectConsultation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelEditExamName;
    private javax.swing.JLabel jLabelEditExamTittle;
    private javax.swing.JPanel jPanelEditExamForm;
    private javax.swing.JPanel jPanelEditExamTittle;
    private javax.swing.JPanel jPanelFrame;
    private javax.swing.JScrollPane jScrollPaneEditExamConsultationComment;
    private javax.swing.JTextArea jTextAreaEditExamConsultationComment;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextFieldEditExamName;
    // End of variables declaration//GEN-END:variables

}
