/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.Exam;

import Controller.ControllerExam;

import View.MainJFrame;

/**
 *
 * @author mateu
 */
public class EditExamJDialog extends javax.swing.JDialog {

    private final MainJFrame frame;
    private final int examId;
    private final String examName;
    private final int treatmentId;
    private final String treatmentName;
    private final int consultationId;
    private final String consultationComment;
    private final int animalId;
    private final String animalName;
    private final int clientId;
    private final String clientName;
    private final int vetId;
    private final String vetName;
    
    /** Creates new form SeeExamJDialog */
    public EditExamJDialog(MainJFrame frame, boolean modal, int examId, String examName, int treatmentId, String treatmentName, int consultationId, String consultationComment, int animalId, String animalName, int clientId, String clientName, int vetId, String vetName) {
        super(frame, modal);
        this.frame = frame;
        this.examId = examId;
        this.examName = examName;
        this.treatmentId = treatmentId;
        this.treatmentName = treatmentName;
        this.consultationId = consultationId;
        this.consultationComment = consultationComment;
        this.animalId = animalId;
        this.animalName = animalName;
        this.clientId = clientId;
        this.clientName = clientName;
        this.vetId = vetId;
        this.vetName = vetName;
        initComponents();
    }

    private String getCurrentExamName() {
        return this.jTextFieldEditExamName.getText();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFrame = new javax.swing.JPanel();
        jPanelEditExamTittle = new javax.swing.JPanel();
        jLabelEditExamTittle = new javax.swing.JLabel();
        jPanelEditExamForm = new javax.swing.JPanel();
        jLabelEditExamName = new javax.swing.JLabel();
        jTextFieldEditExamName = new javax.swing.JTextField();
        jLabelEditExamTreatmentName = new javax.swing.JLabel();
        jTextFieldEditExamTreatmentName = new javax.swing.JTextField();
        jLabelEditExamVetName = new javax.swing.JLabel();
        jTextFieldEditExamVetName = new javax.swing.JTextField();
        jLabelEditExamAnimalName = new javax.swing.JLabel();
        jTextFieldEditExamAnimalName = new javax.swing.JTextField();
        jLabelEditExamClientName = new javax.swing.JLabel();
        jTextFieldEditExamClientName = new javax.swing.JTextField();
        jLabelEditExamConsultationComment = new javax.swing.JLabel();
        jScrollPaneEditExamConsultationComment = new javax.swing.JScrollPane();
        jTextAreaEditExamConsultationComment = new javax.swing.JTextArea();
        jButtonEditExamConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Exam");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanelEditExamTittle.setLayout(new java.awt.BorderLayout());

        jLabelEditExamTittle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelEditExamTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEditExamTittle.setText("Edit Exam");
        jPanelEditExamTittle.add(jLabelEditExamTittle, java.awt.BorderLayout.CENTER);

        jLabelEditExamName.setText("Name");

        jTextFieldEditExamName.setText(this.examName);

        jLabelEditExamTreatmentName.setText("Treatment");

        jTextFieldEditExamTreatmentName.setEditable(false);
        jTextFieldEditExamTreatmentName.setText(this.treatmentName);
        jTextFieldEditExamTreatmentName.setDisabledTextColor(java.awt.Color.black);
        jTextFieldEditExamTreatmentName.setEnabled(false);

        jLabelEditExamVetName.setText("Vet");

        jTextFieldEditExamVetName.setEditable(false);
        jTextFieldEditExamVetName.setText(this.vetName);
        jTextFieldEditExamVetName.setDisabledTextColor(java.awt.Color.black);
        jTextFieldEditExamVetName.setEnabled(false);

        jLabelEditExamAnimalName.setText("Animal");

        jTextFieldEditExamAnimalName.setEditable(false);
        jTextFieldEditExamAnimalName.setText(this.animalName);
        jTextFieldEditExamAnimalName.setDisabledTextColor(java.awt.Color.black);
        jTextFieldEditExamAnimalName.setEnabled(false);

        jLabelEditExamClientName.setText("Client");

        jTextFieldEditExamClientName.setEditable(false);
        jTextFieldEditExamClientName.setText(this.clientName);
        jTextFieldEditExamClientName.setDisabledTextColor(java.awt.Color.black);
        jTextFieldEditExamClientName.setEnabled(false);

        jLabelEditExamConsultationComment.setText("Consultation Comment");

        jTextAreaEditExamConsultationComment.setEditable(false);
        jTextAreaEditExamConsultationComment.setColumns(20);
        jTextAreaEditExamConsultationComment.setRows(5);
        jTextAreaEditExamConsultationComment.setText(this.consultationComment);
        jTextAreaEditExamConsultationComment.setDisabledTextColor(java.awt.Color.black);
        jTextAreaEditExamConsultationComment.setEnabled(false);
        jScrollPaneEditExamConsultationComment.setViewportView(jTextAreaEditExamConsultationComment);

        jButtonEditExamConfirm.setText("Update");
        jButtonEditExamConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEditExamConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditExamConfirmActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelEditExamFormLayout = new org.jdesktop.layout.GroupLayout(jPanelEditExamForm);
        jPanelEditExamForm.setLayout(jPanelEditExamFormLayout);
        jPanelEditExamFormLayout.setHorizontalGroup(
            jPanelEditExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelEditExamFormLayout.createSequentialGroup()
                .add(jLabelEditExamName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(4, 4, 4)
                .add(jTextFieldEditExamName))
            .add(jPanelEditExamFormLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPaneEditExamConsultationComment, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelEditExamFormLayout.createSequentialGroup()
                .add(jLabelEditExamConsultationComment)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(jPanelEditExamFormLayout.createSequentialGroup()
                .add(jPanelEditExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabelEditExamVetName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabelEditExamTreatmentName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabelEditExamAnimalName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabelEditExamClientName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(jPanelEditExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelEditExamFormLayout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(jTextFieldEditExamVetName))
                    .add(jPanelEditExamFormLayout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(jTextFieldEditExamAnimalName))
                    .add(jPanelEditExamFormLayout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(jTextFieldEditExamClientName))
                    .add(jPanelEditExamFormLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextFieldEditExamTreatmentName))))
            .add(jPanelEditExamFormLayout.createSequentialGroup()
                .add(154, 154, 154)
                .add(jButtonEditExamConfirm)
                .add(0, 159, Short.MAX_VALUE))
        );
        jPanelEditExamFormLayout.setVerticalGroup(
            jPanelEditExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelEditExamFormLayout.createSequentialGroup()
                .add(jPanelEditExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelEditExamName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldEditExamName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelEditExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelEditExamTreatmentName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldEditExamTreatmentName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelEditExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelEditExamVetName)
                    .add(jTextFieldEditExamVetName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(9, 9, 9)
                .add(jPanelEditExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldEditExamAnimalName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelEditExamAnimalName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelEditExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldEditExamClientName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelEditExamClientName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabelEditExamConsultationComment, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPaneEditExamConsultationComment, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 35, Short.MAX_VALUE)
                .add(jButtonEditExamConfirm))
        );

        org.jdesktop.layout.GroupLayout jPanelFrameLayout = new org.jdesktop.layout.GroupLayout(jPanelFrame);
        jPanelFrame.setLayout(jPanelFrameLayout);
        jPanelFrameLayout.setHorizontalGroup(
            jPanelFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelEditExamTittle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFrameLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelEditExamForm, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelFrameLayout.setVerticalGroup(
            jPanelFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFrameLayout.createSequentialGroup()
                .add(jPanelEditExamTittle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelEditExamForm, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFrame, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFrame, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditExamConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditExamConfirmActionPerformed
        try {
            ControllerExam.editExam(this.examId,this.getCurrentExamName(),this.consultationId);
            ControllerExam.showDataTableAll(this.frame.getTableComponentsCollection(),this.frame.getTableComponentsExams());
            this.dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println(ex);
            javax.swing.JOptionPane.showMessageDialog(this.frame,ex);
        }
    }//GEN-LAST:event_jButtonEditExamConfirmActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            ControllerExam.showSeeExamJDialogFromExamId(this.frame, this.examId);
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println(ex);
            javax.swing.JOptionPane.showMessageDialog(this.frame, ex);
        }
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditExamConfirm;
    private javax.swing.JLabel jLabelEditExamAnimalName;
    private javax.swing.JLabel jLabelEditExamClientName;
    private javax.swing.JLabel jLabelEditExamConsultationComment;
    private javax.swing.JLabel jLabelEditExamName;
    private javax.swing.JLabel jLabelEditExamTittle;
    private javax.swing.JLabel jLabelEditExamTreatmentName;
    private javax.swing.JLabel jLabelEditExamVetName;
    private javax.swing.JPanel jPanelEditExamForm;
    private javax.swing.JPanel jPanelEditExamTittle;
    private javax.swing.JPanel jPanelFrame;
    private javax.swing.JScrollPane jScrollPaneEditExamConsultationComment;
    private javax.swing.JTextArea jTextAreaEditExamConsultationComment;
    private javax.swing.JTextField jTextFieldEditExamAnimalName;
    private javax.swing.JTextField jTextFieldEditExamClientName;
    private javax.swing.JTextField jTextFieldEditExamName;
    private javax.swing.JTextField jTextFieldEditExamTreatmentName;
    private javax.swing.JTextField jTextFieldEditExamVetName;
    // End of variables declaration//GEN-END:variables

}
