/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.Exam;

import View.MainJFrame;
/**
 *
 * @author mateu
 */
public class NewExamJDialog extends javax.swing.JDialog {
    
    private final MainJFrame frame;
    private final int treatmentId;
    private final String treatmentName;
    private final int consultationId;
    private final String consultationComment;
    private final int animalId;
    private final String animalName;
    private final int clientId;
    private final String clientName;
    private final int vetId;
    private final String vetName;
    
    /** Creates new form NewExamJDialog */
    public NewExamJDialog(MainJFrame frame, boolean modal, int treatmentId, String treatmentName, int consultationId, String consultationComment, int animalId, String animalName, int clientId, String clientName, int vetId, String vetName) {
        super(frame, modal);
        this.frame = frame;
        this.treatmentId = treatmentId;
        this.treatmentName = treatmentName;
        this.consultationId = consultationId;
        this.consultationComment = consultationComment;
        this.animalId = animalId;
        this.animalName = animalName;
        this.clientId = clientId;
        this.clientName = clientName;
        this.vetId = vetId;
        this.vetName = vetName;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFrame = new javax.swing.JPanel();
        jPanelNewExamTittle = new javax.swing.JPanel();
        jLabelNewExamTittle = new javax.swing.JLabel();
        jPanelNewExamForm = new javax.swing.JPanel();
        jLabelNewExamName = new javax.swing.JLabel();
        jTextFieldNewExamName = new javax.swing.JTextField();
        jButtonNewExamSelectConsultation = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPaneNewExamConsultationComment = new javax.swing.JScrollPane();
        jTextAreaNewExamConsultationComment = new javax.swing.JTextArea();
        jButtonNewExamConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Exam");
        setResizable(false);

        jPanelNewExamTittle.setLayout(new java.awt.BorderLayout());

        jLabelNewExamTittle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelNewExamTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNewExamTittle.setText("New Exam");
        jPanelNewExamTittle.add(jLabelNewExamTittle, java.awt.BorderLayout.CENTER);

        jLabelNewExamName.setText("Name");

        jButtonNewExamSelectConsultation.setText("Select Consultation");
        jButtonNewExamSelectConsultation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setText("Treatment");

        jTextField2.setEditable(false);
        jTextField2.setDisabledTextColor(java.awt.Color.black);
        jTextField2.setEnabled(false);

        jLabel5.setText("Vet");

        jTextField3.setEditable(false);
        jTextField3.setDisabledTextColor(java.awt.Color.black);
        jTextField3.setEnabled(false);

        jLabel6.setText("Animal");

        jTextField4.setEditable(false);
        jTextField4.setDisabledTextColor(java.awt.Color.black);
        jTextField4.setEnabled(false);

        jLabel7.setText("Client");

        jTextField5.setEditable(false);
        jTextField5.setDisabledTextColor(java.awt.Color.black);
        jTextField5.setEnabled(false);

        jLabel1.setText("Consultation Comments");

        jTextAreaNewExamConsultationComment.setEditable(false);
        jTextAreaNewExamConsultationComment.setColumns(20);
        jTextAreaNewExamConsultationComment.setRows(5);
        jTextAreaNewExamConsultationComment.setDisabledTextColor(java.awt.Color.black);
        jTextAreaNewExamConsultationComment.setEnabled(false);
        jScrollPaneNewExamConsultationComment.setViewportView(jTextAreaNewExamConsultationComment);

        jButtonNewExamConfirm.setText("Register");
        jButtonNewExamConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        org.jdesktop.layout.GroupLayout jPanelNewExamFormLayout = new org.jdesktop.layout.GroupLayout(jPanelNewExamForm);
        jPanelNewExamForm.setLayout(jPanelNewExamFormLayout);
        jPanelNewExamFormLayout.setHorizontalGroup(
            jPanelNewExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelNewExamFormLayout.createSequentialGroup()
                .add(jLabelNewExamName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(4, 4, 4)
                .add(jTextFieldNewExamName))
            .add(jPanelNewExamFormLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPaneNewExamConsultationComment, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelNewExamFormLayout.createSequentialGroup()
                .add(jLabel1)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(jPanelNewExamFormLayout.createSequentialGroup()
                .add(jPanelNewExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(jPanelNewExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelNewExamFormLayout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(jTextField3))
                    .add(jPanelNewExamFormLayout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(jTextField4))
                    .add(jPanelNewExamFormLayout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(jTextField5))
                    .add(jPanelNewExamFormLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextField2))))
            .add(jPanelNewExamFormLayout.createSequentialGroup()
                .add(jPanelNewExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelNewExamFormLayout.createSequentialGroup()
                        .add(127, 127, 127)
                        .add(jButtonNewExamSelectConsultation))
                    .add(jPanelNewExamFormLayout.createSequentialGroup()
                        .add(154, 154, 154)
                        .add(jButtonNewExamConfirm)))
                .add(0, 0, Short.MAX_VALUE))
        );
        jPanelNewExamFormLayout.setVerticalGroup(
            jPanelNewExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelNewExamFormLayout.createSequentialGroup()
                .add(jPanelNewExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelNewExamName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldNewExamName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonNewExamSelectConsultation)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(9, 9, 9)
                .add(jPanelNewExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPaneNewExamConsultationComment, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButtonNewExamConfirm))
        );

        org.jdesktop.layout.GroupLayout jPanelFrameLayout = new org.jdesktop.layout.GroupLayout(jPanelFrame);
        jPanelFrame.setLayout(jPanelFrameLayout);
        jPanelFrameLayout.setHorizontalGroup(
            jPanelFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelNewExamTittle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFrameLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelNewExamForm, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelFrameLayout.setVerticalGroup(
            jPanelFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFrameLayout.createSequentialGroup()
                .add(jPanelNewExamTittle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewExamForm, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFrame, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFrame, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNewExamConfirm;
    private javax.swing.JButton jButtonNewExamSelectConsultation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelNewExamName;
    private javax.swing.JLabel jLabelNewExamTittle;
    private javax.swing.JPanel jPanelFrame;
    private javax.swing.JPanel jPanelNewExamForm;
    private javax.swing.JPanel jPanelNewExamTittle;
    private javax.swing.JScrollPane jScrollPaneNewExamConsultationComment;
    private javax.swing.JTextArea jTextAreaNewExamConsultationComment;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextFieldNewExamName;
    // End of variables declaration//GEN-END:variables

}
