/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.Exam;

import Controller.ControllerConsultation;
import Controller.ControllerExam;

import View.MainJFrame;
/**
 *
 * @author mateu
 */
public class NewExamJDialog extends javax.swing.JDialog {
    
    private final MainJFrame frame;
    private final int treatmentId;
    private final String treatmentName;
    private final int consultationId;
    private final String consultationComment;
    private final int animalId;
    private final String animalName;
    private final int clientId;
    private final String clientName;
    private final int vetId;
    private final String vetName;
    private boolean showSeeConsultation = true;
    
    /** Creates new form NewExamJDialog */
    public NewExamJDialog(MainJFrame frame, boolean modal, int treatmentId, String treatmentName, int consultationId, String consultationComment, int animalId, String animalName, int clientId, String clientName, int vetId, String vetName) {
        super(frame, modal);
        this.frame = frame;
        this.treatmentId = treatmentId;
        this.treatmentName = treatmentName;
        this.consultationId = consultationId;
        this.consultationComment = consultationComment;
        this.animalId = animalId;
        this.animalName = animalName;
        this.clientId = clientId;
        this.clientName = clientName;
        this.vetId = vetId;
        this.vetName = vetName;
        initComponents();
    }

    private String getCurrentExamName() {
        return this.jTextFieldNewExamName.getText();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFrame = new javax.swing.JPanel();
        jPanelNewExamTittle = new javax.swing.JPanel();
        jLabelNewExamTittle = new javax.swing.JLabel();
        jPanelNewExamForm = new javax.swing.JPanel();
        jLabelNewExamName = new javax.swing.JLabel();
        jTextFieldNewExamName = new javax.swing.JTextField();
        jLabelNewExamTreatmentName = new javax.swing.JLabel();
        jTextFieldNewExamTreatmentName = new javax.swing.JTextField();
        jLabelNewExamVetName = new javax.swing.JLabel();
        jTextFieldNewExamVetName = new javax.swing.JTextField();
        jLabelNewExamAnimalName = new javax.swing.JLabel();
        jTextFieldNewExamAnimalName = new javax.swing.JTextField();
        jLabelNewExamClientName = new javax.swing.JLabel();
        jTextFieldNewExamClientName = new javax.swing.JTextField();
        jLabelNewExamConsultationComment = new javax.swing.JLabel();
        jScrollPaneNewExamConsultationComment = new javax.swing.JScrollPane();
        jTextAreaNewExamConsultationComment = new javax.swing.JTextArea();
        jButtonNewExamConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Exam");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanelNewExamTittle.setLayout(new java.awt.BorderLayout());

        jLabelNewExamTittle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelNewExamTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNewExamTittle.setText("New Exam");
        jPanelNewExamTittle.add(jLabelNewExamTittle, java.awt.BorderLayout.CENTER);

        jLabelNewExamName.setText("Name");

        jLabelNewExamTreatmentName.setText("Treatment");

        jTextFieldNewExamTreatmentName.setEditable(false);
        jTextFieldNewExamTreatmentName.setText(this.treatmentName);
        jTextFieldNewExamTreatmentName.setDisabledTextColor(java.awt.Color.black);
        jTextFieldNewExamTreatmentName.setEnabled(false);

        jLabelNewExamVetName.setText("Vet");

        jTextFieldNewExamVetName.setEditable(false);
        jTextFieldNewExamVetName.setText(this.vetName);
        jTextFieldNewExamVetName.setDisabledTextColor(java.awt.Color.black);
        jTextFieldNewExamVetName.setEnabled(false);

        jLabelNewExamAnimalName.setText("Animal");

        jTextFieldNewExamAnimalName.setEditable(false);
        jTextFieldNewExamAnimalName.setText(this.animalName);
        jTextFieldNewExamAnimalName.setDisabledTextColor(java.awt.Color.black);
        jTextFieldNewExamAnimalName.setEnabled(false);

        jLabelNewExamClientName.setText("Client");

        jTextFieldNewExamClientName.setEditable(false);
        jTextFieldNewExamClientName.setText(this.clientName);
        jTextFieldNewExamClientName.setDisabledTextColor(java.awt.Color.black);
        jTextFieldNewExamClientName.setEnabled(false);

        jLabelNewExamConsultationComment.setText("Consultation Comment");

        jTextAreaNewExamConsultationComment.setEditable(false);
        jTextAreaNewExamConsultationComment.setColumns(20);
        jTextAreaNewExamConsultationComment.setRows(5);
        jTextAreaNewExamConsultationComment.setText(this.consultationComment);
        jTextAreaNewExamConsultationComment.setDisabledTextColor(java.awt.Color.black);
        jTextAreaNewExamConsultationComment.setEnabled(false);
        jScrollPaneNewExamConsultationComment.setViewportView(jTextAreaNewExamConsultationComment);

        jButtonNewExamConfirm.setText("Register");
        jButtonNewExamConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNewExamConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewExamConfirmActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelNewExamFormLayout = new org.jdesktop.layout.GroupLayout(jPanelNewExamForm);
        jPanelNewExamForm.setLayout(jPanelNewExamFormLayout);
        jPanelNewExamFormLayout.setHorizontalGroup(
            jPanelNewExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelNewExamFormLayout.createSequentialGroup()
                .add(jLabelNewExamName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jTextFieldNewExamName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 320, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(jPanelNewExamFormLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPaneNewExamConsultationComment, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelNewExamFormLayout.createSequentialGroup()
                .add(jLabelNewExamConsultationComment)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(jPanelNewExamFormLayout.createSequentialGroup()
                .add(jPanelNewExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabelNewExamVetName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabelNewExamTreatmentName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabelNewExamAnimalName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabelNewExamClientName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 10, Short.MAX_VALUE)
                .add(jPanelNewExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextFieldNewExamAnimalName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextFieldNewExamVetName)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextFieldNewExamTreatmentName)
                    .add(jTextFieldNewExamClientName)))
            .add(jPanelNewExamFormLayout.createSequentialGroup()
                .add(154, 154, 154)
                .add(jButtonNewExamConfirm)
                .add(0, 153, Short.MAX_VALUE))
        );
        jPanelNewExamFormLayout.setVerticalGroup(
            jPanelNewExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelNewExamFormLayout.createSequentialGroup()
                .add(jPanelNewExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelNewExamName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldNewExamName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelNewExamTreatmentName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldNewExamTreatmentName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelNewExamVetName)
                    .add(jTextFieldNewExamVetName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(9, 9, 9)
                .add(jPanelNewExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldNewExamAnimalName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelNewExamAnimalName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewExamFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldNewExamClientName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelNewExamClientName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabelNewExamConsultationComment, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPaneNewExamConsultationComment, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 35, Short.MAX_VALUE)
                .add(jButtonNewExamConfirm))
        );

        org.jdesktop.layout.GroupLayout jPanelFrameLayout = new org.jdesktop.layout.GroupLayout(jPanelFrame);
        jPanelFrame.setLayout(jPanelFrameLayout);
        jPanelFrameLayout.setHorizontalGroup(
            jPanelFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelNewExamTittle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFrameLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelNewExamForm, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelFrameLayout.setVerticalGroup(
            jPanelFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFrameLayout.createSequentialGroup()
                .add(jPanelNewExamTittle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNewExamForm, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFrame, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFrame, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewExamConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewExamConfirmActionPerformed
        try {
            ControllerExam.newExam(this.getCurrentExamName(),this.consultationId);
            ControllerExam.showDataTableAll(this.frame.getTableComponentsCollection(),this.frame.getTableComponentsExams());
            this.showSeeConsultation = false;
            this.dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println(ex);
            javax.swing.JOptionPane.showMessageDialog(this.frame,ex);
        }
    }//GEN-LAST:event_jButtonNewExamConfirmActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            if(showSeeConsultation)
                ControllerConsultation.showSeeConsultationJDialogFromConsultationId(this.frame, this.consultationId);
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println(ex);
            javax.swing.JOptionPane.showMessageDialog(this.frame, ex);
        }
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNewExamConfirm;
    private javax.swing.JLabel jLabelNewExamAnimalName;
    private javax.swing.JLabel jLabelNewExamClientName;
    private javax.swing.JLabel jLabelNewExamConsultationComment;
    private javax.swing.JLabel jLabelNewExamName;
    private javax.swing.JLabel jLabelNewExamTittle;
    private javax.swing.JLabel jLabelNewExamTreatmentName;
    private javax.swing.JLabel jLabelNewExamVetName;
    private javax.swing.JPanel jPanelFrame;
    private javax.swing.JPanel jPanelNewExamForm;
    private javax.swing.JPanel jPanelNewExamTittle;
    private javax.swing.JScrollPane jScrollPaneNewExamConsultationComment;
    private javax.swing.JTextArea jTextAreaNewExamConsultationComment;
    private javax.swing.JTextField jTextFieldNewExamAnimalName;
    private javax.swing.JTextField jTextFieldNewExamClientName;
    private javax.swing.JTextField jTextFieldNewExamName;
    private javax.swing.JTextField jTextFieldNewExamTreatmentName;
    private javax.swing.JTextField jTextFieldNewExamVetName;
    // End of variables declaration//GEN-END:variables

}
